### ISSUE TITLE
Please edit README.md for v1.9

### ISSUE THREAD

**Issue by bopoh13** [preda/gpuowl#1]
I saw the application on the [forum](http://www.mersenneforum.org/showthread.php?t=22204&page=21#post471663). Unfortunately, it is not clear which parameters are required to run the application.
1. The "selftest" parameter remained in the description, but it [was removed](https://github.com/preda/gpuowl/commit/ccb7ed21#diff-d024ebd67a56180eb321b7a5a70e6559) from the program:
https://github.com/preda/gpuowl/blob/cb09cb2cc933667dd7d8fd442e737b62e853cd48/args.h#L54-L55
It would be great if they could update the description.

2. Does the errors affect the calculations or can I ignore it? The parameter "legacy" produces the same error (But the end of the calculated runs through 6 days. That for 1 day is less than without the parameter.)
> gpuOwL v1.9- GPU Mersenne primality checker
AMD Radeon (TM) R7 370 Series 16 @1:0.0, Pitcairn 1015MHz [win7-x64]
OpenCL compilation error -11 (args -I. -cl-fast-relaxed-math -cl-std=CL2.0  -DEX
P=77002949u -DWIDTH=1024u -DHEIGHT=2048u -DLOG_NWORDS=22u -DFP_DP=1 )
An invalid option was specified.

> ".\gpuowl.cl", line 67: warning: OpenCL extension is now part of core
  #pragma OPENCL EXTENSION cl_khr_fp64 : enable
 OpenCL compilation in 1762 ms, with "-I. -cl-fast-relaxed-math  -DEXP=77002949u
-DWIDTH=1024u -DHEIGHT=2048u -DLOG_NWORDS=22u -DFP_DP=1 "

**Comment by preda** [comment]
Thanks, I'll address this in 1week (travelling now).

**Comment by preda** [comment]
- at question 2, by "errors" you mean the warning at line 67? that should be fine. Do you see other errors?

- if "legacy" runs faster, by all means use it. That's why it's there, because sometimes it may be faster.

**Comment by bopoh13** [comment]
Thanks for support! Yes, I see other error (described above):
> OpenCL compilation error -11

Compiling OpenCL happens on my PC? Should I look for other GPU drivers?

**Comment by preda** [comment]
I see now. This is what happens:
- first, it attempts compilation with -cl-std=CL2.0, and this is what produces the error -11. After this fails, it attemps a new compilation (without CL2.0) which this time succeeds (with the warning).
So everything should be fine.

**Comment by bopoh13** [comment]
Much grateful! Then I will not worry. :smile_cat:

**Comment by preda** [comment]
Update README done.

**Comment by soulslicer** [comment]
Hi all,

I am currently developing an OpenCL application. I too have an R7 370. And I have gotten the same error. I am using the latest AMD App SDK. Despite changing my flags to use Version 1.2, I still get the same error:

    #define CL_HPP_MINIMUM_OPENCL_VERSION 120
    #define CL_HPP_TARGET_OPENCL_VERSION 120

How did you guys fix it
