### ISSUE TITLE
Runtime error: assertion failed

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#10]
gpuowl: kernel.h:57: Kernel::Kernel(cl_program ... Assertion ... workSize % groupSize == 0 ... failed

I have compiled the master branch and got this error at runtime. The version displayed by gpuowl is 2.1

System Information:
- Debian testing
- gcc 7.3.0

**Comment by preda** [comment]
Could you please add what is on the previous output line? (there should be the name of the kernel concerned). In fact, it may be useful to add the full gpuowl output at the start, where it reports: exponent, fft-size, gpu model.

**Comment by valeriob01** [comment]
I am using the text console and have no means to copy the output. I will try to redirect it to a file.

**Comment by preda** [comment]
You'll find it in gpuowl.log in the same folder. You can do something like:
"tail -n20 gpuowl.log > report.txt"
to get the last 20 lines in the .txt file.

**Comment by valeriob01** [comment]
Thank you for the help, here is the output:

gpuOwL v2.1--mod GPU Mersenne primality checker
Ellesmere-36x1360-@1:0.0 Radeon RX 580 Series
Note: using long carry and fused tail kernels
OpenCL compilation in 428 ms, with " -DEXP=85219273u -DWIDTH=2048u -DNW=8u -DHEIGHT=2048u -DNH=8u  -I. -cl-fast-relaxed-math -cl-kernel-arg-info "
fftP

**Comment by preda** [comment]
Interesting.. I can't make sense of why that assertion fails. The numbers (WIDTH, HEIGHT, NW, NH) seems correct. The workgroup size for that kernel should be 256, and that assert should pass.

If you do a "git status" or "git diff", do you have local changes? or an old gpuowl.cl? Otherwise, I'm out of ideas on this.

**Comment by valeriob01** [comment]
After copying also the new gpuowl.cl it works now.

gpuOwL v2.1--mod GPU Mersenne primality checker
Ellesmere-36x1360-@1:0.0 Radeon RX 580 Series
Note: using long carry and fused tail kernels
OpenCL compilation in 580 ms, with " -DEXP=85219273u -DWIDTH=2048u -DNW=8u -DHEIGHT=2048u -DNH=8u  -I. -cl-fast-relaxed-math -cl-kernel-arg-info "
[2018-06-02 13:30:15 CEST] PRP M(85219273): FFT 8192K (2048x2048x2), 10.16 bits/word, block 500, at iteration 6093000
OK initial check.
OK [13:30:33]  6094000 / 85219273 [ 7.15%], 6.79 ms/it [6.70, 6.88]; ETA 6d 05:12; dd551f006dcf173d (check 5.43s)
OK [13:31:19]  6100000 / 85219273 [ 7.16%], 6.79 ms/it [6.69, 7.85]; ETA 6d 05:15; 5ab42c570daf9f16 (check 5.46s)

Stopping, please wait..
OK [13:36:34]  6146000 / 85219273 [ 7.21%], 6.72 ms/it [6.70, 7.00]; ETA 6d 03:42; 9841586b45f7b03a (check 5.70s)

Bye
