### ISSUE TITLE
exponent 101230417: FFT too short at 3%

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#101]
-fft +1 to make it work.

**Comment by valeriob01** [comment]
> -fft +1 to make it work.

Stopped at 4%, using -fft +2 now.

**Comment by gwoltman** [comment]
What source code?  New sin/cos code was added hours ago.  If using this new code, please try -use ORIG_SLOWTRIG

**Comment by valeriob01** [comment]
> What source code? New sin/cos code was added hours ago. If using this new code, please try -use ORIG_SLOWTRIG

Using the latest commit of some hour ago. Another exponent M100 is running good with the new code and -use MORE_ACCURATE

ORIG_SLOWTRIG works for now with M101 exponent of above.

**Comment by gwoltman** [comment]
Recommend "-use ORIGINAL_TWEAKED,ORIG_MIDDLEMUL2".   Problem appears to be in the Chebyshev method rather than the new sin/cos code.

**Comment by valeriob01** [comment]
> Recommend "-use ORIGINAL_TWEAKED,ORIG_MIDDLEMUL2". Problem appears to be in the Chebyshev method rather than the new sin/cos code.

Thank you.

**Comment by valeriob01** [comment]
So it is not an FFT issue but other new development accuracy problem. Symptoms: 3 consecutive errors, then gpuowl quits.

**Comment by gwoltman** [comment]
Yes, sorry for the troubles.   It is now fixed.
