### ISSUE TITLE
P-1 requested 652 buffers of 44MB each and blocked

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#105]
`101986949 P2 using 652 buffers of 44.0 MB each`

another M101 exponent requested 47 buffers of 44MB each and is proceeding

**Comment by valeriob01** [comment]
> `101986949 P2 using 652 buffers of 44.0 MB each`
> 
> another M101 exponent requested 47 buffers of 44MB each and is proceeding

second run of same exponents requested 350 buffers of 44MB each. How is the number of buffers calculated ?

**Comment by selroc** [comment]
Maybe an exponent starting P-1 requests N buffers based on free memory, then a second exponent starts and requests what is left?

**Comment by preda** [comment]
Are you running multiple P-1 on the same GPU at the same time?

**Comment by preda** [comment]
I would recommend to run a single P-1 per GPU. If you run multiple, please specify -maxAlloc <size-in-bytes> with less that half of the GPU ram per instance.

It seems there is a problem is free memory reporting. (that is how the number of buffers was calculated)

**Comment by valeriob01** [comment]
> Are you running multiple P-1 on the same GPU at the same time?

I run 1 exponent per GPU, however there are 4 GPUs in the system, it may happen that two or more exponents start P-1 at the same time.

**Comment by preda** [comment]
I still don't understand why this happened. Anyway should be fixed now, give it a try.

**Comment by valeriob01** [comment]
> I still don't understand why this happened. Anyway should be fixed now, give it a try.

It all stands on how std::numeric_limits<size_t>::max()  is evaluated !

**Comment by selroc** [comment]
> I still don't understand why this happened. Anyway should be fixed now, give it a try.

this test P-1 requested 353 buffers which is 15532MB.

**Comment by preda** [comment]
Can you reproduce the problem after the latest commit?

**Comment by valeriob01** [comment]
> Can you reproduce the problem after the latest commit?

No. I am waiting for another exponent to finish, the next exponent should do P-1 and so I will be able to tell for sure.

**Comment by valeriob01** [comment]
> > Can you reproduce the problem after the latest commit?
> 
> No. I am waiting for another exponent to finish, the next exponent should do P-1 and so I will be able to tell for sure.

This time it requested 343 buffers, 15092MB.

**Comment by valeriob01** [comment]
> > > Can you reproduce the problem after the latest commit?
> > 
> > 
> > No. I am waiting for another exponent to finish, the next exponent should do P-1 and so I will be able to tell for sure.
> 
> This time it requested 343 buffers, 15092MB.

3 exponents all requested 343 buffers. OK.
