### ISSUE TITLE
Add gpu mem display

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#106]
https://github.com/preda/gpuowl/blob/fd01ee5ae6dcc37da5c441932854ae7d0ce71ff6/Args.cpp#L75

It could be useful to display gpu total mem after AMD/not-AMD.
the function getTotalMem() should work for both AMD and not-AMD I hope.

**Comment by valeriob01** [comment]
I am currently unable to add this myself. The though behind this is to provide complete gpu info to the user upon program startup.

**Comment by valeriob01** [comment]
> I am currently unable to add this myself. The though behind this is to provide complete gpu info to the user upon program startup.

Complete gpu info could be like this:
Cache size, Max clock, Memory size, Vendor, Name.

https://github.com/valeriob01/gpuinfo

**Comment by preda** [comment]
Yes I think I can add GPU total memory probably, but why? what is the need?
The user does have "clinfo" which provides pretty much all the info about a GPU.

**Comment by valeriob01** [comment]
> Yes I think I can add GPU total memory probably, but why? what is the need?
> The user does have "clinfo" which provides pretty much all the info about a GPU.

Yes that's true but clinfo is a separate program not always installed by default, so if gpuowl provides that info it is a quicker way to look at it. Of course it is not necessary, just a nice addition.
