### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#122]
It is possible to use C++ instead of python to monitor GPU usage. The library is https://github.com/GPUOpen-Tools/gpu_performance_api

Would you like to start developing a monitor program in C++ ?

**Comment by valeriob01** [comment]
It is really weird that you do not reply to my questions in a timely manner like you did before.

**Comment by preda** [comment]
Sorry for that.
Now, about a GPU monitor in C++, it's not something I feel the need to be doing, not right now. Maybe somebody else could be doing that, or maybe it exists already. The small python tool that's with GpuOwl was just a small solution to a personal need, I don't see that growing into a full-fledged GPU monitor regardless of language.

About the performance library you pointed to, I did have a quick look, but again I didn't see a clear benefit in using it now. Maybe I'll have another look in the future.
