### ISSUE TITLE
Result lost after blackout

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#124]
The exponent was completed but result not written in results.txt file and not in sent.txt file.
I think the blackout was just in the middle of result writing.
One checkpoint was invalid, backup checkpoint was good.

**Comment by valeriob01** [comment]
must add that the checkpoint is for the next exponent, the previous exponent result is lost.

**Comment by valeriob01** [comment]
And the worktodo.txt file was empty, the proof is that I got 3 new tasks in that file.

**Comment by preda** [comment]
So you did lose a full exponent? that's not good. Are you using -clean to remove the exponent folder once it's completed? I'll look into making the writing of a result more durable.

**Comment by valeriob01** [comment]
> So you did lose a full exponent? that's not good. Are you using -clean to remove the exponent folder once it's completed? I'll look into making the writing of a result more durable.

I'm not using -clean, just had a blackout I think in the middle of result/worktodo writing.

**Comment by preda** [comment]
Most likely the checkpoints are not lost. Look into gpuowl.log, find the exponent, and add it again to worktodo.txt, which should start it from very near the end and produce a result. If you still have the assignment on mersenne.org you can get the assignemnt from there.

**Comment by valeriob01** [comment]
> Most likely the checkpoints are not lost. Look into gpuowl.log, find the exponent, and add it again to worktodo.txt, which should start it from very near the end and produce a result. If you still have the assignment on mersenne.org you can get the assignemnt from there.

OK, I have recovered the exponent from the log file and as you said it re-produced a result in a few seconds:

![image](https://user-images.githubusercontent.com/25838910/77310870-5d89e580-6cff-11ea-81d7-fd4bce421665.png)

and primenet.py has to return it soon.

**Comment by valeriob01** [comment]
OK result returned.

**Comment by valeriob01** [comment]
(ref. https://mersenneforum.org/showthread.php?p=550649#post550649)

After some more experimentation I found the following:

- For M105-M106 exponents (the current PRP wavefront) both checkpoints are invalid after blackout and I need to run `remove_checkpoints_by_size. sh` to restart computing from scratch;
- For M332-M333 exponents (current PRP_M100 wavefront) only one checkpoint is invalid, and the computation can restart from the previous one.

My system is Ubuntu Focal Fossa with ROCm 3.3

**Comment by valeriob01** [comment]
re-closing, copied the post to the correct issue: https://github.com/preda/gpuowl/issues/81
