### ISSUE TITLE
updating in the middle of WIP

### ISSUE THREAD

**Issue by selroc** [preda/gpuowl#130]
Proposal: There should be warnings that the current commit is WIP, otherwise we risk to block production for an update.

**Comment by preda** [comment]
To which commit do you refer to?

**Comment by valeriob01** [comment]
> To which commit do you refer to? AFAIK no commit broke anything (aside from unknown bugs..)

I wish I could write better in english, I was not referring to any particular commit, it is a general proposal for the future.

**Comment by valeriob01** [comment]
Besides that, let me say that I think you are an extraordinary programmer and I wish you well.

**Comment by preda** [comment]
In general we never publish (at least not intentionally) "breaking commits" that leave the code in a broken state, even if that state is temporary. OTOH some commits are important changes, while other commits a small cosmetic changes with no impact.

**Comment by valeriob01** [comment]
> In general we never publish (at least not intentionally) "breaking commits" that leave the code in a broken state, even if that state is temporary. OTOH some commits are important changes, while other commits a small cosmetic changes with no impact.

thisis a wise decision my dear :-)
