### ISSUE TITLE
Ubuntu and ROCm 3.3 fails to load libOpenCL.so.1

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#133]
./gpuowl -h
./gpuowl: error while loading shared libraries: libOpenCL.so.1: cannot open shared object file: No such file or directory

This is Ubuntu and ROCm 3.3

**Comment by valeriob01** [comment]
I have installed ocl-icd-opencl-dev and recompiled and now I get:

./gpuowl -h
2020-04-02 09:17:34 gpuowl v6.11-242-g27fc32f-dirty

Command line options:

-dir <folder>      : specify local work directory (containing worktodo.txt, results.txt, config.txt, gpuowl.log)
-pool <dir>        : specify a directory with the shared (pooled) worktodo.txt and results.txt
                     Multiple GpuOwl instances, each in its own directory, can share a pool of assignments and report
                     the results back to the common pool.
-uid <unique_id>   : specifies to use the GPU with the given unique_id (only on ROCm/Linux)
-user <name>       : specify the user name.
-cpu  <name>       : specify the hardware name.
-time              : display kernel profiling information.
-fft <size>        : specify FFT size, such as: 5000K, 4M, +2.
-block <value>     : PRP GEC block size. Default 400. Smaller block is slower but detects errors sooner.
-log <step>        : log every <step> iterations, default 200000. Multiple of 10000.
-carry long|short  : force carry type. Short carry may be faster, but requires high bits/word.
-B1                : P-1 B1 bound, default 1000000
-B2                : P-1 B2 bound, default B1 * 30
-rB2               : ratio of B2 to B1. Default 30, used only if B2 is not explicitly set
-cleanup           : delete save files at end of run
-prp <exponent>    : run a single PRP test and exit, ignoring worktodo.txt
-pm1 <exponent>    : run a single P-1 test and exit, ignoring worktodo.txt
-results <file>    : name of results file, default 'results.txt'
-iters <N>         : run next PRP test for <N> iterations and exit. Multiple of 10000.
-maxAlloc          : limit GPU memory usage to this value in MB (needed on non-AMD GPUs)
-yield             : enable work-around for CUDA busy wait taking up one CPU core
-nospin            : disable progress spinner
-use NEW_FFT8,OLD_FFT5,NEW_FFT10: comma separated list of defines, see the #if tests in gpuowl.cl (used for perf tuning)
-device <N>        : select a specific device:
free(): invalid pointer
Aborted (core dumped)

**Comment by valeriob01** [comment]
also rocm-smi works but clinfo  core dumps

**Comment by valeriob01** [comment]
and : 


./gpuowl -user selroc -cpu R7a -block 1000 -log 20000 -device 0
2020-04-02 09:27:53 gpuowl v6.11-242-g27fc32f-dirty
2020-04-02 09:27:53 Note: not found 'config.txt'
2020-04-02 09:27:53 config: -user selroc -cpu R7a -block 1000 -log 20000 -device 0 
2020-04-02 09:27:53 device 0, unique id ''
2020-04-02 09:27:53 R7a 102943807 FFT 5632K: Width 256x4, Height 64x4, Middle 11; 17.85 bits/word
2020-04-02 09:27:53 R7a Expected maximum carry32: 3F780000
2020-04-02 09:27:53 R7a Exception gpu_error: DEVICE_NOT_FOUND clGetDeviceIDs(platforms[i], kind, 64, devices, &n) at clwrap.cpp:77 getDeviceIDs
2020-04-02 09:27:53 R7a Bye

**Comment by valeriob01** [comment]
Please tell me how to resolve this if you can (I have already lost 6 hours trying to resolve this).

**Comment by valeriob01** [comment]
downgrading to ROCm 3.1 did not do any good. Now I have the same platform as you do but still getting core dumps. Where is the magic ?

**Comment by preda** [comment]
This really isn't a gpuowl issue -- please discuss ROCm issues on their forum.

Did you install libncurses5 ? (as strange as that sounds)

**Comment by valeriob01** [comment]
> This really isn't a gpuowl issue -- please discuss ROCm issues on their forum.
> 
> Did you install libncurses5 ? (as strange as that sounds)

I just did it and this resolved the issue :-)
However this is not documented in ROCm docs.

**Comment by valeriob01** [comment]
https://github.com/RadeonOpenCompute/ROCm/issues/1067
