### ISSUE TITLE
Q: what is the difference in linking to amdocl64 instead of OpenCL ?

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#134]
Is it faster?

**Comment by preda** [comment]
No, it is the same performance. libOpenCL loads amdocl64 in the end, so the result is the same. The difference is in how the target lib (amdocl64) is found -- libOpenCL uses ICD files e.g. /etc/OpenCL/vendors/amdocl64.icd ; while linking amdocl64 directly uses LD_LIBRARY_PATH.
