### ISSUE TITLE
primenet.py task type 153

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#138]
Does it actually get PRP_DC ?
I started an instance with it and got 332M exponent.

**Comment by preda** [comment]
Could you please compare with what you get if you request PRP-DC on the manual asssignment web page? Otherwise no idea why it gives such huge exponent.. strange. Could be a DC though, you can look at the exponent and see if it had a PRP done.

**Comment by valeriob01** [comment]
I did and got an 82M exponent.

**Comment by valeriob01** [comment]
BTW, it is an exponent that you did PRP before.

**Comment by valeriob01** [comment]
and the 332M exponent has no PRP before.

**Comment by preda** [comment]
workTypes = dict(PRP=150, PRP_FIRST=150, PRP_DC=151, PRP_WORLD_RECORD=152, PRP_100M=153, PF=4, PM1=4)

So, 153 corresponds to PRP_100M, and it seems that's what you have. DC is 151.

**Comment by selroc** [comment]
> workTypes = dict(PRP=150, PRP_FIRST=150, PRP_DC=151, PRP_WORLD_RECORD=152, PRP_100M=153, PF=4, PM1=4)
> 
> So, 153 corresponds to PRP_100M, and it seems that's what you have. DC is 151.

Thank you.

**Comment by valeriob01** [comment]
> workTypes = dict(PRP=150, PRP_FIRST=150, PRP_DC=151, PRP_WORLD_RECORD=152, PRP_100M=153, PF=4, PM1=4)
> 
> So, 153 corresponds to PRP_100M, and it seems that's what you have. DC is 151.

Ok, but then the positions here are incorrect...

-w {PF,PRP_FIRST,PRP_100M,PRP_WORLD_RECORD,PRP_DC,PM1,PRP,150,151,152,153,4} GIMPS work type

**Comment by selroc** [comment]
> > workTypes = dict(PRP=150, PRP_FIRST=150, PRP_DC=151, PRP_WORLD_RECORD=152, PRP_100M=153, PF=4, PM1=4)
> > So, 153 corresponds to PRP_100M, and it seems that's what you have. DC is 151.
> 
> Ok, but then the positions here are incorrect...
> 
> -w {PF,PRP_FIRST,PRP_100M,PRP_WORLD_RECORD,PRP_DC,PM1,PRP,150,151,152,153,4} GIMPS work type

To make it more clear it could be useful to specify these as follows:

{mnemonic/number, mnemonic/number, mnemonic/number, ..... }

what do you think about this?
