### ISSUE TITLE
work type 151

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#139]
The new assignments are got as PRP=...
Should I change this to DoubleCheck=... in the worktodo.txt file ?

**Comment by preda** [comment]
No. These are PRP double checks, they are processed in the same way as any PRP test.
If you change to DoubleCheck, it would do an LL test, which would be a waste as it does not double-check the previous PRP.

**Comment by preda** [comment]
Probably primenet.py does not offer LL DCs yet.
