### ISSUE TITLE
Invalid JSON output for PM1 jobs

### ISSUE THREAD

**Issue by dgcampea** [preda/gpuowl#143]
Using one of the test-cases for PM1, we get the following result:
```
{"status":"F", "exponent":"86005021", "worktype":"PM1", "B1":"15015", "fft-length":"4718592", "factors":"["43592319559794136631809"]", "program":{"name":"gpuowl", "version":"v6.11-259-g83434d8"}, "computer":"gfx803-0", "timestamp":"2020-04-15 19:16:56 UTC"}
```

Notice the `factor` key. It has `string` as its value type instead of an `array` (quotes surrounding the square brackets). This causes primenet to reject Factor Found results since it's expecting an `array` for the factor key.

**Comment by preda** [comment]
Thank you! fixed now.
