### ISSUE TITLE
FFT selection

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#16]
An exponent > 86.5M started with 4M FFT produced errors at around 20%. Same exponent restarted with 5M FFT now appears going OK.

**Comment by valeriob01** [comment]
Full log of computation with error:

[gpuowl.log](https://github.com/preda/gpuowl/files/2495115/gpuowl.log)

Computation now restarted with -fft +1 proceeds ok.

**Comment by preda** [comment]
this should be fixed some time ago

**Comment by valeriob01** [comment]
An exponent 332xxxxxx started with 18M FFT produced errors at around 6%. Same exponent restarted with -fft +2 now is making progress.

**Comment by preda** [comment]
thanks. You can change the FFT size in the middle (at 6% on error). Could you give me a more precise value of the exponent?

**Comment by valeriob01** [comment]
332252xxx. I changed FFT with -fft +2 and it works.
