### ISSUE TITLE
About PRP Proof

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#160]
I have been reading your post https://mersenneforum.org/showthread.php?p=546633#post546633
The cost of transferring the proof file is asymmetric for most user-lines, upload is more costly than download as user-lines are, for the vast majority of users, asymmetric digital subscriber lines (ADSL), the cost in time drops with Fiber, but still it is asymmetric. Thus the uploader has the major cost. A 120MB file can be about 20 minutes of upload time for some low-end lines. However, for flat lines, it does not add cost in money.

**Comment by valeriob01** [comment]
The cost of local storage, about 6GB, isn't much of a concern to me, as modern hard drives are 500GB for a small cost.

**Comment by valeriob01** [comment]
> The cost of local storage, about 6GB, isn't much of a concern to me, as modern hard drives are 500GB for a small cost.

You can get a 1TB hard drive for 40 euro (44,03 dollars).

**Comment by valeriob01** [comment]
Also, to avoid duplicating the cost of transmitting the proof file, it is desirable that it file is kept and archived by the server, possibly in a lossless compression format.

**Comment by valeriob01** [comment]
You said "The disk space required would be on the order of 2TB for every 1M exponent range (because: 18K not-factored candidates per 1M range x 120MB)."

I guess you are talking about uncompressed file storage. Let's consider file compression algorithms. For plain ASCII the winner is LZMA (21.39% of the original), see https://binfalse.de/2011/04/04/comparison-of-compression/ and Wikipedia https://en.wikipedia.org/wiki/Lempel%E2%80%93Ziv%E2%80%93Markov_chain_algorithm .

**Comment by valeriob01** [comment]
> You said "The disk space required would be on the order of 2TB for every 1M exponent range (because: 18K not-factored candidates per 1M range x 120MB)."
> 
> I guess you are talking about uncompressed file storage. Let's consider file compression algorithms. For plain ASCII the winner is LZMA (21.39% of the original), see https://binfalse.de/2011/04/04/comparison-of-compression/ and Wikipedia https://en.wikipedia.org/wiki/Lempel%E2%80%93Ziv%E2%80%93Markov_chain_algorithm .

Let's says it, LZMA is _slow_, but achieves the best compression ratio for ASCII.

**Comment by preda** [comment]
The proof should not be compressible at all. I'll verify this.

**Comment by valeriob01** [comment]
> The proof should not be compressible at all. I'll verify this.

for binary data LZMA is still the winner (88.84% of the original) however the slowness may be a bottleneck and I am not sure anymore that it is worth doing it.

**Comment by valeriob01** [comment]
IMHO you should continue do dig deep into VDF. There is much gain there. Example: 332M exponents are now done in 9 days 4 hours with Radeon VII. The VDF could allow DC in far shorter time.

**Comment by preda** [comment]
Thanks for support, yes the discussion is advancing positivelly.
