### ISSUE TITLE
P-1 problems: excessive saving, kworker leak; and some comments about "shift"

### ISSUE THREAD

**Issue by a-repko** [preda/gpuowl#163]
I noticed that P-1 stage 1 saves the work every 5 minutes with no regard to other parameters or hardware. It becomes a problem for large exponents, e.g. 100M digit, which saves a 40 MB file. It amounts to 11 GB of SSD wear per day. Stage 2 saves the file only at the new block, which makes 160 MB per 4 minutes on Radeon VII, which is around 30 GB per day. I think this has a not negligible impact on SSD life, with no real advantage (moreover, it seems that iteration time is prolonged during the saving). Currently, I'm circumventing this by creating a RAMdisk for each exponent, e.g.
`mount -t tmpfs -o size=640M none /path/to/gpuowl/332500061`
Of course, if I have already some save-file, I need to copy it around during mounting.

The second problem is some additive CPU load which is caused by each completed P-1 assignment. I noticed that after completing five 100M-digit P-1 assignments, there is a constant 45% CPU "system" load which belongs to a process "kworker/0:3-events" (probably some kernel resource is not deallocated after use; it is fixed to one specific CPU-core). So it cost me a total of 3 core-hours after these 5 exponents (although this particular CPU (AMD Jaguar) is quite slow, it serves well for the Radeon VII hosting, and is also doing one specific work-type, for which it is very efficient). Of course, restarting gpuowl brings the CPU-load again to normal, but this is not really a sustainable solution.

I have also one comment to the discussion "the shift - to be or not to be" ;-). Although Gerbicz check is apparently very good at detecting errors, there is one type of data corruption, which goes undetected by it (as far as I understand it): when you change the iteration count by a multiple of 400. Moreover, if this change is repeatable by some software error, then you produce a false double-check. However, shift-enabled calculation will lead to a different residue. By the way: shift-zero Jacobi check seems to be vulnerable to any iteration-count drift.

Other vulnerabilites can be caused by saving only one residue (the Gerbicz one). I assume that to guard the data integrity, you do at least this: save the (I-400)_G (Gerbicz) residue and also res64 of the actual residue at (I). Then, at next start, you can calculate (I)-residue by 3*((I-400)_G)^(2^400-1) and compare whether the res64 matches. So, if you do at least this check, then we should be relatively safe (of course, not counting the above iteration-counter drift corruption).

Last (but not least): why do you not include res2048 to your JSON output?

PS: I'm using the gpuowl version from 15th May 2020, but I hope to upgrade soon to get the Jacobi check.

**Comment by preda** [comment]
The first problem: I don't think 30GB or ever 100GB of data written per 24h should be something to worry to much about. I can reduce the time between saves in the first stage to e.g. every 10min. I don't plan to change the save schedule for stage2 though (do you have any proposal what the change should be there?)

Problem2: is not related to gpuowl at all. It's a amdgpu (the kernel component) problem, and was already fixed in recent kernels. Was also reported on ROCm-issues.

Thanks for pointing out the 400-step weakness for GEC, I agree. I'm moving towards productivizing the proof mecanism which is independent of GEC and much stronger. I don't plan to add shift AKA offset to either LL or PRP yet, I still don't see the need.

Yes that's pretty much how the PRP load is done. You can check the source code for reference.

I can include the res2048, but will it be accepted by the server?

**Comment by a-repko** [comment]
OK, 10 minute interval is better, but I just expected the P-1 stage 1 to respect the -log option in the same way as PRP or LL. The stage 2 schedule is OK, since at least it doesn't increase the SSD wear with decreasing GPU performance (i.e. always the same amount of data is written per job; given the amount of RAM is the same).

ad 2: Good to know. I have gentoo 5.4.28 stable kernel compiled May 9. There is a newer one - 5.4.38 (I don't know if it includes the fix). Anyway I'm not going to recompile the kernel every 2 weeks, so the matter will wait some time. Also, I'm using ROCm 3.1, because mfakto kernels don't compile properly with 3.3

As for res2048 - I didn't follow the discussion all the time, but as I remember, this was introduced in Prime95/mprime to enable quick [kind-of-PRP test on cofactor](https://www.mersenneforum.org/showthread.php?t=23462) if a new factor is found. But I don't know whether server accepts it also from other programs.

Maybe I will leave this open for some time, as I expect that these points can be of interest also for others.

**Comment by preda** [comment]
I think the kworker was fixed in Linux kernel 5.6 or 5.7.
