### ISSUE TITLE
Can't build 

### ISSUE THREAD

**Issue by CheetahGod** [preda/gpuowl#164]
Using ubuntu 18.04 and Roc 3.3

 make
echo \"`git describe --long --dirty --always`\" > version.new
fatal: not a git repository (or any of the parent directories): .git
diff -q -N version.new version.inc >/dev/null || mv version.new version.inc
echo Version: `cat version.inc`
Version: ""
g++ -MT Pm1Plan.o -MMD -MP -MF .d/Pm1Plan.Td -Wall -O2 -std=c++17   -c -o Pm1Plan.o Pm1Plan.cpp
g++ -MT GmpUtil.o -MMD -MP -MF .d/GmpUtil.Td -Wall -O2 -std=c++17   -c -o GmpUtil.o GmpUtil.cpp
g++ -MT Worktodo.o -MMD -MP -MF .d/Worktodo.Td -Wall -O2 -std=c++17   -c -o Worktodo.o Worktodo.cpp
g++ -MT common.o -MMD -MP -MF .d/common.Td -Wall -O2 -std=c++17   -c -o common.o common.cpp
g++ -MT main.o -MMD -MP -MF .d/main.Td -Wall -O2 -std=c++17   -c -o main.o main.cpp
g++ -MT Gpu.o -MMD -MP -MF .d/Gpu.Td -Wall -O2 -std=c++17   -c -o Gpu.o Gpu.cpp
g++ -MT clwrap.o -MMD -MP -MF .d/clwrap.Td -Wall -O2 -std=c++17   -c -o clwrap.o clwrap.cpp
g++ -MT Task.o -MMD -MP -MF .d/Task.Td -Wall -O2 -std=c++17   -c -o Task.o Task.cpp
g++ -MT checkpoint.o -MMD -MP -MF .d/checkpoint.Td -Wall -O2 -std=c++17   -c -o checkpoint.o checkpoint.cpp
g++ -MT timeutil.o -MMD -MP -MF .d/timeutil.Td -Wall -O2 -std=c++17   -c -o timeutil.o timeutil.cpp
g++ -MT Args.o -MMD -MP -MF .d/Args.Td -Wall -O2 -std=c++17   -c -o Args.o Args.cpp
g++ -MT state.o -MMD -MP -MF .d/state.Td -Wall -O2 -std=c++17   -c -o state.o state.cpp
g++ -MT Signal.o -MMD -MP -MF .d/Signal.Td -Wall -O2 -std=c++17   -c -o Signal.o Signal.cpp
g++ -MT FFTConfig.o -MMD -MP -MF .d/FFTConfig.Td -Wall -O2 -std=c++17   -c -o FFTConfig.o FFTConfig.cpp
g++ -MT AllocTrac.o -MMD -MP -MF .d/AllocTrac.Td -Wall -O2 -std=c++17   -c -o AllocTrac.o AllocTrac.cpp
g++ -MT gpuowl-wrap.o -MMD -MP -MF .d/gpuowl-wrap.Td -Wall -O2 -std=c++17   -c -o gpuowl-wrap.o gpuowl-wrap.cpp
g++ -o gpuowl Pm1Plan.o GmpUtil.o Worktodo.o common.o main.o Gpu.o clwrap.o Task.o checkpoint.o timeutil.o Args.o state.o Signal.o FFTConfig.o AllocTrac.o gpuowl-wrap.o -lstdc++fs -lOpenCL -lgmp -pthread -L/opt/rocm-3.3.0/opencl/lib/x86_64 -L/opt/rocm-3.1.0/opencl/lib/x86_64 -L/opt/rocm/opencl/lib/x86_64 -L/opt/amdgpu-pro/lib/x86_64-linux-gnu -L.
Task.o: In function `Proof::verify(Gpu*)':
Task.cpp:(.text._ZN5Proof6verifyEP3Gpu[_ZN5Proof6verifyEP3Gpu]+0x1e9): undefined reference to `SHA3Init(SHA3Context*, int)'
Task.cpp:(.text._ZN5Proof6verifyEP3Gpu[_ZN5Proof6verifyEP3Gpu]+0x20d): undefined reference to `SHA3Update(SHA3Context*, unsigned char const*, unsigned int)'
Task.cpp:(.text._ZN5Proof6verifyEP3Gpu[_ZN5Proof6verifyEP3Gpu]+0x21e): undefined reference to `SHA3Final(SHA3Context*)'
Task.cpp:(.text._ZN5Proof6verifyEP3Gpu[_ZN5Proof6verifyEP3Gpu]+0x2d6): undefined reference to `SHA3Init(SHA3Context*, int)'
Task.cpp:(.text._ZN5Proof6verifyEP3Gpu[_ZN5Proof6verifyEP3Gpu]+0x2e8): undefined reference to `SHA3Update(SHA3Context*, unsigned char const*, unsigned int)'
Task.cpp:(.text._ZN5Proof6verifyEP3Gpu[_ZN5Proof6verifyEP3Gpu]+0x2f6): undefined reference to `SHA3Update(SHA3Context*, unsigned char const*, unsigned int)'
Task.cpp:(.text._ZN5Proof6verifyEP3Gpu[_ZN5Proof6verifyEP3Gpu]+0x2fe): undefined reference to `SHA3Final(SHA3Context*)'
Task.o: In function `ProofSet::computeProof(Gpu*, unsigned long)':
Task.cpp:(.text._ZN8ProofSet12computeProofEP3Gpum[_ZN8ProofSet12computeProofEP3Gpum]+0x1eb): undefined reference to `SHA3Init(SHA3Context*, int)'
Task.cpp:(.text._ZN8ProofSet12computeProofEP3Gpum[_ZN8ProofSet12computeProofEP3Gpum]+0x20a): undefined reference to `SHA3Update(SHA3Context*, unsigned char const*, unsigned int)'
Task.cpp:(.text._ZN8ProofSet12computeProofEP3Gpum[_ZN8ProofSet12computeProofEP3Gpum]+0x21b): undefined reference to `SHA3Final(SHA3Context*)'
Task.cpp:(.text._ZN8ProofSet12computeProofEP3Gpum[_ZN8ProofSet12computeProofEP3Gpum]+0x29b): undefined reference to `SHA3Init(SHA3Context*, int)'
Task.cpp:(.text._ZN8ProofSet12computeProofEP3Gpum[_ZN8ProofSet12computeProofEP3Gpum]+0x2ab): undefined reference to `SHA3Update(SHA3Context*, unsigned char const*, unsigned int)'
Task.cpp:(.text._ZN8ProofSet12computeProofEP3Gpum[_ZN8ProofSet12computeProofEP3Gpum]+0x2b8): undefined reference to `SHA3Update(SHA3Context*, unsigned char const*, unsigned int)'
Task.cpp:(.text._ZN8ProofSet12computeProofEP3Gpum[_ZN8ProofSet12computeProofEP3Gpum]+0x2c0): undefined reference to `SHA3Final(SHA3Context*)'
Task.cpp:(.text._ZN8ProofSet12computeProofEP3Gpum[_ZN8ProofSet12computeProofEP3Gpum]+0x616): undefined reference to `SHA3Init(SHA3Context*, int)'
Task.cpp:(.text._ZN8ProofSet12computeProofEP3Gpum[_ZN8ProofSet12computeProofEP3Gpum]+0x626): undefined reference to `SHA3Update(SHA3Context*, unsigned char const*, unsigned int)'
Task.cpp:(.text._ZN8ProofSet12computeProofEP3Gpum[_ZN8ProofSet12computeProofEP3Gpum]+0x633): undefined reference to `SHA3Update(SHA3Context*, unsigned char const*, unsigned int)'
Task.cpp:(.text._ZN8ProofSet12computeProofEP3Gpum[_ZN8ProofSet12computeProofEP3Gpum]+0x63b): undefined reference to `SHA3Final(SHA3Context*)'
collect2: error: ld returned 1 exit status
Makefile:19: recipe for target 'gpuowl' failed
make: *** [gpuowl] Error 1

**Comment by preda** [comment]
The first errors indicate that you're not building in a git directory.
The linking errors have just been fixed in a commit now.

**Comment by CheetahGod** [comment]
What os do you reccomend? Also I can't find ROCm 1.7 only version 3.3

**Comment by CheetahGod** [comment]
When i run /opt/rocm/bin/rocminfo

ROCk module is loaded
jason is member of video group
hsa api call failure at: /data/jenkins-workspace/compute-rocm-rel-3.3/rocminfo/rocminfo.cc:1102
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.
**

**Comment by CheetahGod** [comment]
I have a r9 270. Is that supported by rocm?

**Comment by valeriob01** [comment]
> I have a r9 270. Is that supported by rocm?

from the ROCm docs:

GFX7 GPUs

    "Hawaii" chips, such as the AMD Radeon R9 390X and FirePro W9100

**Comment by preda** [comment]
I don't know whether r9 270 is supported by ROCm.. I don't have experience with that GPU, sorry. Feel free to ask on "ROCm issues" somebody may know there.
