### ISSUE TITLE
Does the PRP Proof include time and date?

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#174]
Inclusion of time and date is necessary to certify who found the prime first, if two users pretend to have found a prime at same time.

**Comment by preda** [comment]
Normally a PRP Proof is accompanied (preceded) by the usual JSON PRP result, which includes both date/time and the composite/probable-prime status.

**Comment by preda** [comment]
The proof file itself does not include a timestamp.

**Comment by valeriob01** [comment]
Thanks for the explanation, closing.
