### ISSUE TITLE
-tmpDir and Proof files

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#176]
Ref.: https://mersenneforum.org/showpost.php?p=551168&postcount=112

Good catch !
I am also pointing the tmpDir to a NFS mount where the server has a BIG hard disk.

Besides, I have already two proof files stored locally, how are they reported?

**Comment by preda** [comment]
The upload is in works. Probably there will be a tool (a stanalone executable of sorts) that will upload the proofs.

**Comment by valeriob01** [comment]
Are there any special actions one has to take in order to receive CERT work? perhaps a CERT work type?

**Comment by preda** [comment]
CERT is not supported in GpuOwl (or planned) ATM.
