### ISSUE TITLE
Primenet.py, pool dir, proof upload, different work types

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#180]
How well primenet.py works with the new proof upload from a pool directory if I am getting different work types for each GPU ?
I still need to run multiple primenet.py instances each with a different -w argument, does it work well when specifying different pool dirs for different instances?

**Comment by preda** [comment]
Yes is supposed to work if you keep the primenet.py invocation unchanged; but please report any problems.

**Comment by valeriob01** [comment]
Just completed an exponent's PRP and proof upload worked fine without a pool dir...I think I'll leave things unchanged for now.

**Comment by valeriob01** [comment]
![image](https://user-images.githubusercontent.com/25838910/88450468-7510e080-ce4f-11ea-8169-e718ff6e39d8.png)

**Comment by valeriob01** [comment]
The "Success" line is never printed !!

**Comment by valeriob01** [comment]
> The "Success" line is never printed !!

and the successive result is printed on the same line:
![image](https://user-images.githubusercontent.com/25838910/88471119-553bf400-cf05-11ea-8f41-14fe9c0bc967.png)

**Comment by preda** [comment]
Is this still an issue?

**Comment by valeriob01** [comment]
No. Closing.
