### ISSUE TITLE
Along the lines of PRP-Proof: W3C Verifiable Credentials

### ISSUE THREAD

**Issue by selroc** [preda/gpuowl#185]
I know this goes beyond the current scope of gpuOwl, however for the GIMPS project it could be useful to implement verifiable credentials to certify user identity in such a way that the same user identity cannot be stolen or impersonated by another user.
Verifiable Credentials make extensive use of JSON-LD (https://www.w3.org/TR/2020/REC-json-ld11-20200716/).

https://www.w3.org/TR/2019/NOTE-vc-imp-guide-20190924/#dfn-verifiable-credentials

Excerpt of the document (from the Terminology):

claim
    An assertion made about a subject.

credential
    A set of one or more claims made by an issuer. A verifiable credential is a tamper-evident credential that has authorship that can be cryptographically verified. Verifiable credentials can be used to build verifiable presentations, which can also be cryptographically verified. The claims in a credential can be about different subjects. 
...
issuer
    A role an entity can perform by asserting claims about one or more subjects, creating a verifiable credential from these claims, and transmitting the verifiable credential to a holder. 
...
4. Verification
This section is non-normative.

Verification is the process a verifier or holder performs when presented with a verifiable presentation or verifiable credential. Verification includes checking the presented item against the core data model, and may also include validating the provided proof section and checking the item's status.
...
4.3.2 Verifiable Data Registries

A verifiable data registry can also provide content integrity protection. One example of a verifiable data registry which provides content integrity protection is a distributed ledger. This is a shared transaction record which provides mechanisms for verifying the content it stores. These mechanisms include consensus protocols, digital signatures, and verifiable data structures such as Merkle trees. These mechanisms provide cryptographic assurances that the content retrieved from the ledger has not been altered, and is complete.

**Comment by selroc** [comment]
The reason I wrote this is I find insufficient for a GIMPS task result to transmit only the username, that is easily impersonated by a third party. Verifiable credentials could make it possible to certify the user identity, and provide a secure user identity verification channel for eventual transactions in case of prime discovery.
At the moment I cannot quantify the effort necessary to implement, but we could, together, come up with something usable.
Please let me know your opinion about this.

**Comment by preda** [comment]
I think this is out of scope for GpuOwl. Feel free to propose and discuss the idea on the mersenne forums.

**Comment by selroc** [comment]
Unfortunately I cannot write on Mersenne forum. But can I ask you to propose this improvement on my behalf ?

**Comment by preda** [comment]
Try to get write access to the forum back.

**Comment by selroc** [comment]
I think this is not possible, some moderators behaved adversely.
