### ISSUE TITLE
gpuowl 7 slower than 6

### ISSUE THREAD

**Issue by selroc** [preda/gpuowl#194]
![image](https://user-images.githubusercontent.com/55827668/95693624-95219600-0c2d-11eb-87c1-f548baf99f4a.png)

whereas gpuowl 6 is faster:

![image](https://user-images.githubusercontent.com/55827668/95693695-ef225b80-0c2d-11eb-8002-259bf269bdf6.png)

**Comment by preda** [comment]
The way those numbers are computed changed. For example the check time is not accounted separately anymore. Other than that, it's not actually slower. Will look into improving the way time is displayed.

**Comment by selroc** [comment]
The ETA is about 2-3 hours higher on gpuowl 7.

**Comment by selroc** [comment]
Is the ETA precise and accountable?

**Comment by valeriob01** [comment]
It is actually important that the ETA is reliable because gpuowl cannot be timed with the Linux 'time' command as the process never ends.

**Comment by preda** [comment]
No, the ETA is no accurate, it is simply a projection (or extension) of the reported number over the length of the test. I would expect the new ETA may be more accurate than the old ETA. 

To time with "time" use "-iters <N>" and the process will end.

**Comment by valeriob01** [comment]
Ok, or I can just put only one exponent in worktodo.txt. Using -iters assumes I know how many iterations per exponent, which is easy though :-)

Can I ask why -maxAlloc is now mandatory ?  Isn't it easier to let the program select the more appropriate value?

**Comment by valeriob01** [comment]
> Ok, or I can just put only one exponent in worktodo.txt. Using -iters assumes I know how many iterations per exponent, which is easy though :-)
> 
> Can I ask why -maxAlloc is now mandatory ? Isn't it easier to let the program select the more appropriate value?

did I ask a question, or is it just a figment of my imagination ?

:-)

**Comment by preda** [comment]
> Can I ask why -maxAlloc is now mandatory ? Isn't it easier to let the program select the more appropriate value?

Well, how would the program select the more appropriate value? (I don't know how to do that).
With -maxAlloc, the user indicates how he wants to split the GPU physical memory between the various things he runs on the GPU. Maybe one app, maybe two, maybe app + display, a game, etc.

**Comment by selroc** [comment]
Can I set -maxAlloc 16G on Radeon VII ?

**Comment by preda** [comment]
That would be a bad idea, because some other small amounts of GPU RAM are already in use, so you don't have 16GB available on the R7 ever. Once you go over the top, even a bit, everything slows to a crawl.

Instead, if you're running nothing else on the R7, set -maxAlloc to 15G and monitor memory use during P-1 (as it's only P-1 that uses tons of memory, the PRP is small).

**Comment by valeriob01** [comment]
I should be safe with 16G then, I only do PRP, not the PRP_P1 ...

**Comment by selroc** [comment]
I asked for PRP in primenet.py, but got PRP_P1 anyway.

**Comment by preda** [comment]
that's just what PRP always was

**Comment by valeriob01** [comment]
Everything looks fairly normal. Closing.

**Comment by valeriob01** [comment]
> That would be a bad idea, because some other small amounts of GPU RAM are already in use, so you don't have 16GB available on the R7 ever. Once you go over the top, even a bit, everything slows to a crawl.
> 
> Instead, if you're running nothing else on the R7, set -maxAlloc to 15G and monitor memory use during P-1 (as it's only P-1 that uses tons of memory, the PRP is small).

Yes, PRP only uses 3% of 16G on Radeon VII.

**Comment by valeriob01** [comment]
> > That would be a bad idea, because some other small amounts of GPU RAM are already in use, so you don't have 16GB available on the R7 ever. Once you go over the top, even a bit, everything slows to a crawl.
> > Instead, if you're running nothing else on the R7, set -maxAlloc to 15G and monitor memory use during P-1 (as it's only P-1 that uses tons of memory, the PRP is small).
> 
> Yes, PRP only uses 3% of 16G on Radeon VII.

P-1 is consuming 87% of maxAlloc 14G.

**Comment by preda** [comment]
Could be, this depends also on the size of the exponent. Using less than
maxAlloc is not a problem, a problem would be to go over maxAlloc even a
tiny bit which is not allowed and would raise an exception.

**Comment by valeriob01** [comment]
Yes, both GPUs are doing P-1 right now on 108xxxxxx exponents, and both consume 87% of 14G.
