### ISSUE TITLE
VERSION printed twice

### ISSUE THREAD

**Issue by selroc** [preda/gpuowl#197]
![Screenshot from 2020-10-25 03-50-55](https://user-images.githubusercontent.com/55827668/97097823-f148d900-1675-11eb-88af-3ff9e803852c.png)

**Comment by preda** [comment]
Yes I know. They are not the same though -- if you look in the gpuowl.log file, it's only once. The first line goes to the screen only before the log file is even located.

**Comment by selroc** [comment]
That's ok, this is harmless.
