### ISSUE TITLE
proof validation

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#198]
I use -proof 8 -autoverify 8 and it seems to work.
suggestions?

**Comment by preda** [comment]
That's fine too. In that setup the proof validation takes 0.4%.

**Comment by valeriob01** [comment]
I am fine with 0.4%, I must admit that I got 2 "error free" Radeon VII, each one computes a whole exponent with zero errors. Since I got them I have zero errors on all computed exponents.
