### ISSUE TITLE
Some Sanity check fails

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#20]
# cppcheck --enable=all --quiet .
[GCD.cpp:38]: (warning) Assert statement calls a function which may have desired side effects: 'isOngoing'.
[GCD.h:11]: (style) The class 'GCD' does not have a constructor.
[kernel.h:31]: (warning) Member variable 'Kernel::timeSum' is not initialized in the constructor.
[kernel.h:31]: (warning) Member variable 'Kernel::nCalls' is not initialized in the constructor.
[clwrap.h:78]: (style) Class 'Queue' has a constructor with 1 argument that is not explicit.
[Primes.h:18]: (style) Class 'Primes' has a constructor with 1 argument that is not explicit.
[./Result.cpp:24]: (information) Skipping configuration 'REV' since the value of 'REV' is unknown. Use -D if you want to check it. You can use -U to skip it explicitly.
[Worktodo.cpp:26]: (warning) %d in format string (no. 2) requires 'int *' but the argument type is 'unsigned int *'.
[common.cpp:16]: (warning) Return value of function fopen() is not used.
[common.cpp:16]: (error) Return value of allocation function 'fopen' is not stored.
[./gpuowl.cpp:13]: (information) Skipping configuration 'REV' since the value of 'REV' is unknown. Use -D if you want to check it. You can use -U to skip it explicitly.
(information) Cppcheck cannot find all the include files (use --check-config for details)

**Comment by valeriob01** [comment]
Hi Mihai, I have rerun cppcheck locally, there is still 1 warning and 1 error, let alone the style issue:

gpuowl_5.0/gpuowl$ cppcheck --enable=all --quiet .
[GCD.h:11]: (style) The class 'GCD' does not have a constructor.
[./Result.cpp:24]: (information) Skipping configuration 'REV' since the value of 'REV' is unknown. Use -D if you want to check it. You can use -U to skip it explicitly.
**[common.cpp:16]: (warning) Return value of function fopen() is not used.
[common.cpp:16]: (error) Return value of allocation function 'fopen' is not stored.**
[./gpuowl.cpp:13]: (information) Skipping configuration 'REV' since the value of 'REV' is unknown. Use -D if you want to check it. You can use -U to skip it explicitly.
(information) Cppcheck cannot find all the include files (use --check-config for details)

**Comment by preda** [comment]
I don't get the warning+error when I run cppcheck with the same arguments on my system. I also looked at the source at that location, and it seems to me that cppcheck is wrong (it's a red herring).

**Comment by valeriob01** [comment]
> I don't get the warning+error when I run cppcheck with the same arguments on my system. I also looked at the source at that location (common.cpp:16), and it seems to me that cppcheck is wrong (it's a red herring).

Hi Mihai, my system is: #1 SMP Debian 4.9.130-2 (2018-10-27)

this is the output of uname -v command, can you post yours?

**Comment by valeriob01** [comment]
I am running version 1.76.1 of cppcheck, it is probably earlier than your version.
