### ISSUE TITLE
gpuOwl 7.2 - mild slowdown

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#200]
from 6xx us/it to 706 us/it, exponent 106xxxxxx.

**Comment by preda** [comment]
Please try with two processes per GPU.

**Comment by valeriob01** [comment]
1359 us/it, however this way the GEC time is doubled.
Not worth it.

**Comment by preda** [comment]
Why not worth it? if you run 2 processes in parallel, you should divide all
the times by 2; 1360/2 = 680, and doubled-GEC/2 stays the same.

**Comment by valeriob01** [comment]
I prefer the classical way of 1 job per GPU, it makes me feel the system is more stable.

**Comment by preda** [comment]
Sure that's fine, I also run one GPU in one-task-only. The slowdown is
mild, there is a moderated decrease in memory allocation at the same time,
and who knows maybe things will improve in the future (i.e. the slowdown
being cancelled) hopefully, we'll see.

**Comment by valeriob01** [comment]
ROCm 3.9 is out, not testing it for now. I am busy with other things. :-)

**Comment by preda** [comment]
I tried it, no improvement for me.

**Comment by valeriob01** [comment]
Mild speedup with latest commit, from 706 us/it to 696 us/it.

**Comment by valeriob01** [comment]
Big speedup with carry32, from 696 us/it to 680 us/it.
