### ISSUE TITLE
Debian: SCons

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#22]
https://wiki.debian.org/UpstreamGuide#SCons

"Please don't use SCons. It is hard to use it correctly. For instance SCons is designed to ignore environment variables such as CFLAGS (unless your add code for this). It also does not support DESTDIR out of the box. As an upstream you have to explicitly add code for that (or Debian has to patch). Support for SONAMEs (library versioning) is also absent. The general observation is that many projects, that use SCons, do not have a working install target. Since projects work around these limitations individually there is no way to just use a SCons project in Debian, but more work is required to invoke it correctly. "

**Comment by preda** [comment]
There is also a Makefile for dual build (make or scons). I'm going to maintain the Makefile as well. I personally like scons because of the automatic dependency inference.
