### ISSUE TITLE
NTT2 branch (Radeon Pro VII)

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#235]
Compilation is good for NTT2 branch with ROCm 4.3 with the exception of one warning:

`Gpu.cpp:496:5: warning: 'u32 {anonymous}::checkStepForErrors(u32, u32)' defined but not used [-Wunused-function]`

gouowl starts then crashes:

`Segmentation fault (core dumped)`

**Comment by preda** [comment]
I'm not working on that branch ATM. Rpro7 is rather good at FP64.
