### ISSUE TITLE
Wiki Typo

### ISSUE THREAD

**Issue by MiWeiss** [preda/gpuowl#243]
In the [Wiki](https://github.com/preda/gpuowl/wiki) (which, btw., is very helpful 👍) I _think_ there might be a wrong link:

the ` Pietrzak's paper` link points to https://eprint.iacr.org/2018/623.pdf when I think it should probably point to https://eprint.iacr.org/2018/627.pdf (note the last changed digit `3` -> `7`)?

**Comment by preda** [comment]
Hi, thank you, I fixed it now!
Cheers,
Mihai

**Comment by MiWeiss** [comment]
Thanks :-)
