### ISSUE TITLE
Document work-{n}.txt work files

### ISSUE THREAD

**Issue by Morilli** [preda/gpuowl#282]
It seems that currently either the `-pool` argument need to be supplied with a `worktodo.txt` file in the pool directory, or a `work-{n}.txt` in the current directory (or `-dir`'s directory).

This is currently not documented and leads to failure on start when `-pool` is not specified and only a `worktodo.txt` file exists.
Maybe there should be a fallback to that file when `-pool` wasn't specified that is currently missing?

Tested on latest master (4c839afa4a109a2e47452026adbfca5a8e111261).

**Comment by preda** [comment]
Indeed. Attempted to fix in the most recent commit, please verify. I'll also update the docs with some worktodo instructions.

**Comment by preda** [comment]
Updated the pre-built binaries for 0.7 to include the fix.
