### ISSUE TITLE
gpuowl stops if memlock-0 folder already exists

### ISSUE THREAD

**Issue by efvb** [preda/gpuowl#287]
I was running gpuowl-v7.5-10-g61a08e2 for Windows built by Kriesel, link at mersenne forum.

The run was successful, then this step started:
"Released memory lock 'memlock-0' "

When it reached "proof level 3 ..." Windows update restarted my pc :D
Then when I restarted gpuowl it stopped at '"Released memory lock 'memlock-0' " and did not go forward, process was 0% use in Task Manager.

My workaround was to delete the empty "memlock-0" folder inside gpuowl folder.
Then the calculations finished as expected.

**Comment by preda** [comment]
Indeed, this behavior is a bit annoying but rare. When the process crashes, it may leave the lock folder behind, which then needs to be cleaned up manually.

A better alternative would be to include the PID as part of the lock name, allowing the lock attempt to verify that the locker process is still around. I leave this issue open as a feature-request in that direction.

**Comment by preda** [comment]
I guess this remains as-is for now.
