### ISSUE TITLE
OSX_Support :: MakeFile and File.h Updates

### ISSUE THREAD

**Issue by deacon-mp** [preda/gpuowl#292]
Makefile::
`# Use "make DEBUG=1" for a debug build`

`# The build artifacts are put in the "build-release" subfolder (or "build-debug" for a debug build).`

`# Uncomment below as desired to set a particular compiler or force a debug build:`
`# CXX = g++-12`
`# DEBUG = 1`
`# or export those into environment, or pass on the command line e.g.`
`# make all DEBUG=1 CXX=g++-12`

`COMMON_FLAGS = -Wall -std=c++20 -v`
`# -static-libstdc++ -static-libgcc`
`# -fext-numeric-literals`

`ifeq ($(DEBUG), 1)`

`BIN=build-debug`

`CXXFLAGS = -g $(COMMON_FLAGS)`
`STRIP=`

`else`

`BIN=build-release`

`CXXFLAGS = -O2 -DNDEBUG $(COMMON_FLAGS)`
`STRIP=-s`

`endif`

`SRCS1 = fs.cpp TuneEntry.cpp Primes.cpp tune.cpp CycleFile.cpp TrigBufCache.cpp Event.cpp Queue.cppTimeInfo.cpp` 
`Profile.cpp bundle.cpp Saver.cpp KernelCompiler.cpp Kernel.cpp gpuid.cpp File.cpp Proof.cpp log.cpp Worktodo.cpp ``common.cpp main.cpp Gpu.cpp clwrap.cpp Task.cpp timeutil.cpp Args.cpp state.cpp Signal.cpp FFTConfig.cpp` `AllocTrac.cpp sha3.cpp md5.cpp version.cpp`

`SRCS2 = test.cpp`

`# SRCS=$(addprefix src/, $(SRCS1))`

`OBJS = $(SRCS1:%.cpp=$(BIN)/%.o)`
`DEPDIR := $(BIN)/.d`
`$(shell mkdir -p $(DEPDIR) >/dev/null)`
`DEPFLAGS = -MT $@ -MMD -MP -MF $(DEPDIR)/$*.Td`
`COMPILE.cc = $(CXX) $(DEPFLAGS) $(CXXFLAGS) $(CPPFLAGS) $(TARGET_ARCH) -c`
`POSTCOMPILE = @mv -f $(DEPDIR)/$*.Td $(DEPDIR)/$*.d && touch $@`

`all: prpll`

`prpll: $(BIN)/prpll`

`amd: $(BIN)/prpll-amd`

`#$(BIN)/test: $(BIN)/test.o`
`#	$(CXX) $(CXXFLAGS) -o $@ $< $(LIBPATH) ${STRIP}`

`$(BIN)/prpll: ${OBJS}`
`#	$(CXX) $(CXXFLAGS) -o $@ ${OBJS} -lpthread -lOpenCL ${STRIP}`
	$(CXX) $(CXXFLAGS) -o $@ ${OBJS} -lpthread -lOpenCL -lstdc++ ${STRIP}`

`# Instead of linking with libOpenCL, link with libamdocl64`
`$(BIN)/prpll-amd: ${OBJS}`
`	$(CXX) $(CXXFLAGS) -o $@ ${OBJS} -lamdocl64 -L/opt/rocm/lib ${STRIP}`

`clean:`
`	rm -rf build-debug build-release`

`$(BIN)/%.o : src/%.cpp $(DEPDIR)/%.d`
`	$(COMPILE.cc) $(OUTPUT_OPTION) $<`
`	$(POSTCOMPILE)`

`# src/bundle.cpp is just a wrapping of the OpenCL sources (*.cl) as a C string.`

`src/bundle.cpp: genbundle.sh src/cl/*.cl`
`	./genbundle.sh $^ > src/bundle.cpp`

`$(DEPDIR)/%.d: ;`
`.PRECIOUS: $(DEPDIR)/%.d`

`#src/version.cpp : src/version.inc`

`src/version.inc: FORCE`
`	echo \"`basename \`git describe --tags --long --dirty --always --match v/prpll/*\``\" > $(BIN)/version.new`
`	diff -q -N $(BIN)/version.new $@ >/dev/null || mv $(BIN)/version.new $@`
`	echo Version: `cat $@``

`FORCE:`

`include $(wildcard $(patsubst %,$(DEPDIR)/%.d,$(basename $(SRCS1))))`
`# include $(wildcard $(patsubst %,$(DEPDIR)/%.d,$(basename $(SRCS2))))`

src/File.h::
58 |     fsync(fileno(f));

**Comment by preda** [comment]
Please prepare a pull request with the diff.

**Comment by proski** [comment]
#289 has a better fix for `File.h`. Please feel free to reuse. The rest of #289 is probably misguided and useless.

**Comment by preda** [comment]
In the end, does it run on MacOS? what hardware and OS version was it tested on?

**Comment by proski** [comment]
I was able to make prpll compile on MacOS with Apple Silicon, but it was failing to load the OpenCL code. I made bad hacks to work around the unsupported 80-bit `long double`. That should be fixable in principle, perhaps with an extra library. But I don't have time and expertise to fix the OpenCL code.

Even the latest XCode doesn't support C++20 filesystem operations, so I used gcc from Homebrew.

I can have a look at supporting Intel Macs, that might be easier.

**Comment by proski** [comment]
Things are much simpler on x86_64. I was able to make a cleaner PR #294 that doesn't attempt to support Apple Silicon. Something is still not working, but it fails much further down the road. It's even possible that everything would work with different hardware.

**Comment by proski** [comment]
I think this issue can be closed. The fix is in the master branch. The build is working.

Having gpuowl actually work on MacOS is a separate issue.

**Comment by preda** [comment]
Thanks @proski
Your contributions are appreciated!

**Comment by proski** [comment]
I believe prpll requires OpenCL 2.0, but MacOS stopped at OpenCL 1.2 and won't support newer OpenCL versions. I would expect prpll to report that clearly. Support for OpenCL 1.2 would allow MacOS users with recent hardware to participate, which would be great, but I don't know if it's realistic. For now, mfakto can be used on Apple Silicon, and it's quite fast.

**Comment by preda** [comment]
@proski on what GPU do you run mfakto? is it the integrated M2/M3/M4 GPU that can be found for example in a recent Macbook Air, or is it some discrete GPU?

In the past we didn't have any success with running on integrated GPUs (such as found on Intel/AMD CPUs), but the Apple Mx may be different / more powerful.

**Comment by proski** [comment]
> @proski on what GPU do you run mfakto? is it the integrated M2/M3/M4 GPU that can be found for example in a recent Macbook Air, or is it some discrete GPU?
> 
> In the past we didn't have any success with running on integrated GPUs (such as found on Intel/AMD CPUs), but the Apple Mx may be different / more powerful.

I was able to run mfakto on an M2 MacBook Pro with integrated graphics. I can also run mfakto on iMac (model of 2019) with Intel CPU and Radeon (I have to disable the cl_barrett15_74_gs kernel, as it fails the self-test). I also have an older MacBook Pro with Intel GPU (model of 2011), it cannot run mfakto and doesn't appear to have OpenCL.
