### ISSUE TITLE
multiple instances of gpuowl

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#4]
When running multiple instances of gpuowl it may happen that one instance remains stuck and the only way to stop it is to reboot the machine.

Probably the first instance running gets stuck when launching the second instance.

For the precision, the two instances are launched with a different -device gpu number.

**Comment by preda** [comment]
Could you please specify OS, driver (e.g. amdgpu-pro, ROCm) + version, and GPU hardware.
Most likely this might be a driver (OpenCL) issue. But I should try to reproduce it.

**Comment by valeriob01** [comment]
The OS is Debian-testing with amdgpu-pro (latest version, but I will post the version number tomorrow);
The GPU is Asus Radeon RX 580.

**Comment by valeriob01** [comment]
The version of amdgpu-pro is 17.50-511655

**Comment by valeriob01** [comment]
I forgot to mention the sdk with which I compile gpuowl: AMD APP SDK v3.0.130.136-GA-linux64

**Comment by valeriob01** [comment]
After wrestling with amdgpu-pro I am now doing another test with ROCm...

**Comment by valeriob01** [comment]
Back to amdgpu-pro, and resolved the issue by reconfiguring the hardware.
