### ISSUE TITLE
Version string

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#43]
./gpuowl -h
2019-04-14 13:01:47 gpuowl 005297a
2019-04-14 13:01:47 config: -h

**Comment by preda** [comment]
Interesting, did you do a git pull? that should pull in the tag "v6.5".
What is the output of:
git tag --list
? (should show "v6.5" if you see the tag).

**Comment by valeriob01** [comment]
I did git pull origin master

the git tag --list is empty list, no output

**Comment by valeriob01** [comment]
and:

# make
echo \"`git describe --long --dirty --always`\" > version.inc
echo Version: `cat version.inc`
Version: "e26c8c1"
g++ -Wall -O2 -std=c++17 -Wall Pm1Plan.cpp GmpUtil.cpp Worktodo.cpp common.cpp gpuowl.cpp Gpu.cpp clwrap.cpp Task.cpp checkpoint.cpp timeutil.cpp Args.cpp state.cpp Signal.cpp FFTConfig.cpp -o gpuowl -lOpenCL -lgmp -lstdc++fs -pthread -L/opt/rocm/opencl/lib/x86_64 -L/opt/amdgpu-pro/lib/x86_64-linux-gnu -L/c/Windows/System32 -L.

**Comment by valeriob01** [comment]
I know what happens: git pull origin master doesn't get the tag, but git pull does.

**Comment by valeriob01** [comment]
Now:

make
echo \"`git describe --long --dirty --always`\" > version.inc
echo Version: `cat version.inc`
Version: "v6.5-9-ge26c8c1"
g++ -Wall -O2 -std=c++17 -Wall Pm1Plan.cpp GmpUtil.cpp Worktodo.cpp common.cpp gpuowl.cpp Gpu.cpp clwrap.cpp Task.cpp checkpoint.cpp timeutil.cpp Args.cpp state.cpp Signal.cpp FFTConfig.cpp -o gpuowl -lOpenCL -lgmp -lstdc++fs -pthread -L/opt/rocm/opencl/lib/x86_64 -L/opt/amdgpu-pro/lib/x86_64-linux-gnu -L/c/Windows/System32 -L.
