### ISSUE TITLE
Accumulating checkpoint files *.owl

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#50]
We need a way to manage checkpoint files. They accumulate in the gpuowl directory, the directory becomes huge in size after some time of continuous work. In some scenarios the directory must be copied forth and back over the network, and the growing directory size has increasing impact.
A script that removes old checkpoints based on the date could be very useful.

**Comment by valeriob01** [comment]
Maybe something like this:

rmckpt.py \<date\>

python script removes all checkpoints before \<date\>

**Comment by preda** [comment]
Can probably be done with "find" filtered by date piped to "rm"; but I'm not sure such script belongs in the project.

**Comment by valeriob01** [comment]
Thanks! Your comment prompted me to investigate a bit. It can be done like this (substitute -exec ls {} + with -exec rm {} +):

find . -name '*.owl' -a -mtime -30 -exec ls {} +

**Comment by valeriob01** [comment]
find . -name '*.owl' -a -mtime -30 -exec rm {} +

the -30 argument is how far back you want to look, 30 days here.

**Comment by valeriob01** [comment]
> Thanks! Your comment prompted me to investigate a bit. It can be done like this (substitute -exec ls {} + with -exec rm {} +):
> 
> find . -name '*.owl' -a -mtime -30 -exec ls {} +



> Can probably be done with "find" filtered by date piped to "rm"; but I'm not sure such script belongs in the project.

This script belongs to a Mersenne-gpu-computing-node. It is specific for gpuowl though.
