### ISSUE TITLE
Error on Ubuntu/amdgpu-pro 18.50

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#53]
2019-05-23 14:40:05 Note: no config.txt file found
2019-05-23 14:40:05 config: -prp 82589933 -device 0 
2019-05-23 14:40:05 82589933 FFT 4608K: Width 256x4, Height 64x4, Middle 9; 17.50 bits/word
2019-05-23 14:40:05 using short carry kernels
2019-05-23 14:40:09 OpenCL args "-DEXP=82589933u -DWIDTH=1024u -DSMALL_HEIGHT=256u -DMIDDLE=9u -DFRAC=9280343354015947889ul  -I. -cl-fast-relaxed-math -cl-std=CL2.0"
2019-05-23 14:40:10 OpenCL compilation error -11 (args -DEXP=82589933u -DWIDTH=1024u -DSMALL_HEIGHT=256u -DMIDDLE=9u -DFRAC=9280343354015947889ul  -I. -cl-fast-relaxed-math -cl-std=CL2.0)
2019-05-23 14:40:10 /tmp/OCL1986T0.cl:183:3: error: implicit declaration of function '__asm' is invalid in C99
  X2(u[0], u[2]);
  ^
/tmp/OCL1986T0.cl:150:2: note: expanded from macro 'X2'
        __asm( "v_add_f64 %0, %1, -%2\n" : "=v" (b.x) : "v" (t.x), "v" (b.x)); \
        ^
/tmp/OCL1986T0.cl:183:3: error: expected ')'
/tmp/OCL1986T0.cl:150:35: note: expanded from macro 'X2'
        __asm( "v_add_f64 %0, %1, -%2\n" : "=v" (b.x) : "v" (t.x), "v" (b.x)); \
                                         ^
/tmp/OCL1986T0.cl:183:3: note: to match this '('
/tmp/OCL1986T0.cl:150:7: note: expanded from macro 'X2'
        __asm( "v_add_f64 %0, %1, -%2\n" : "=v" (b.x) : "v" (t.x), "v" (b.x)); \
             ^
/tmp/OCL1986T0.cl:183:3: error: expected ')'
  X2(u[0], u[2]);
  ^
/tmp/OCL1986T0.cl:151:35: note: expanded from macro 'X2'
        __asm( "v_add_f64 %0, %1, -%2\n" : "=v" (b.y) : "v" (t.y), "v" (b.y)); \
                                         ^
/tmp/OCL1986T0.cl:183:3: note: to match this '('
/tmp/OCL1986T0.cl:151:7: note: expanded from macro 'X2'
        __asm( "v_add_f64 %0, %1, -%2\n" : "=v" (b.y) : "v" (t.y), "v" (b.y)); \
             ^
/tmp/OCL1986T0.cl:184:3: error: expected ')'
  X2_mul_t4(u[1], u[3]);
  ^
/tmp/OCL1986T0.cl:172:35: note: expanded from macro 'X2_mul_t4'
        __asm( "v_add_f64 %0, %1, -%2\n" : "=v" (t.x) : "v" (b.x), "v" (t.x)); \
                                         ^
/tmp/OCL1986T0.cl:184:3: note: to match this '('
/tmp/OCL1986T0.cl:172:7: note: expanded from macro 'X2_mul_t4'
        __asm( "v_add_f64 %0, %1, -%2\n" : "=v" (t.x) : "v" (b.x), "v" (t.x)); \
             ^
/tmp/OCL1986T0.cl:184:3: error: expected ')'
  X2_mul_t4(u[1], u[3]);
  ^
/tmp/OCL1986T0.cl:173:35: note: expanded from macro 'X2_mul_t4'
        __asm( "v_add_f64 %0, %1, -%2\n" : "=v" (b.x) : "v" (t.y), "v" (b.y)); \
                                         ^
/tmp/OCL1986T0.cl:184:3: note: to match this '('
/tmp/OCL1986T0.cl:173:7: note: expanded from macro 'X2_mul_t4'
        __asm( "v_add_f64 %0, %1, -%2\n" : "=v" (b.x) : "v" (t.y), 2019-05-23 14:40:10 Exception 9gpu_error: BUILD_PROGRAM_FAILURE clBuildProgram at clwrap.cpp:215 build
2019-05-23 14:40:10 Bye

**Comment by preda** [comment]
As a stop-gap you can use "-use ORIG_X2" ; I'll look for a better fix.

**Comment by valeriob01** [comment]
> As a stop-gap you can use "-use ORIG_X2" ; I'll look for a better fix.

Ok it works.

**Comment by valeriob01** [comment]
> > As a stop-gap you can use "-use ORIG_X2" ; I'll look for a better fix.
> 
> Ok it works.

As a test I have attempted to fix the issue myself, by substituting -std=c++17 with -std=gnu++17 but there is no difference.

**Comment by preda** [comment]
on a fresh version, try "-use NO_ASM"

**Comment by valeriob01** [comment]
> on a fresh version, try "-use NO_ASM"

Just updated and tried:

NO_ASM works on amdgpu-pro.

Tried different combinations:

"-use NO_ASM" alone: OK same speed as -use ORIG_X2;

"-use NO_ASM -use ORIG_X2": OK same speed as -use ORIG_X2;

"-use NO_ASM -use INLINE_X2" fails with same error.

**Comment by preda** [comment]
ok, closing for now.
