### ISSUE TITLE
Proposal for improvement of checkpoint recovery mechanism

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#57]
https://github.com/preda/gpuowl/blob/f34ad183b35ce00db1fd3a92d943e58afd997956/checkpoint.cpp#L61

If the checkpoint is invalid, load *-prev.owl, and overwrite the last checkpoint file.

**Comment by valeriob01** [comment]
This proposal should handle the case when after a power loss the checkpoint file is invalid, when a power loss happens while writing the checkpoint. In this case the file is not being closed and remains without the end-of-file mark. On reboot a filesystem check is done, which truncates the checkpoint file to length zero.

**Comment by preda** [comment]
Yes I agree it should handle the invalid checkpoint file in the way you describe. I'll look into implementing this at some point.

**Comment by preda** [comment]
ok, should be done now.

**Comment by valeriob01** [comment]
Thank you. Before I do an update for 3 machines, I have read the code of last commit.
the savefile extension is -old in the new code, but I have only -prev in my gpuowl directory.
Did you change the extension ?

**Comment by preda** [comment]
Yes. There's a post in the GpuOwl thread on mersenneforum explaining the
savefile changes.
