### ISSUE TITLE
Please add cpu name or device number to output lines

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#6]
Just in case one wants to run multiple instances o gpuowl, this is to distinguish the output of each instance.

**Comment by preda** [comment]
The recommended way to run multi-instance is: run each instance in a separate folder, with separate worktodo.txt, results.txt, and gpuowl.log files.

If you run multi instances in the same folder, they'll step on each other's toes when updating worktodo.txt.

**Comment by valeriob01** [comment]
That is what I do, basically I have a set of directories numbered progressively. The problem is that I launch gpuowl instances from a script, all in the same text console, and it is difficult to keep up with the output from each instance.

**Comment by preda** [comment]
OK I see. Fine, I'll think to add this.

**Comment by valeriob01** [comment]
Thank you for this feature, it will help program and system diagnostics.

**Comment by valeriob01** [comment]
At the risk of being redundant, can I ask you to add the cpuname to the lines starting with "OK loaded" and "OK check", because when launching multiple instances, depending on the timing, those lines can get intermingled. It would be nice to be able to unequivocally identify all those lines, and the cpuname is just what is needed. :-)
