### ISSUE TITLE
The line with "load" information disappeared

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#66]
![image](https://user-images.githubusercontent.com/25838910/66293582-45f0a900-e8e7-11e9-9125-a014b2a34600.png)

Gpuowl does not show the line with the "load" information.

**Comment by preda** [comment]
I think this in not caused by NO_ASM, but by some of my recent changes (where I removed the load line). I can look into adding it back if you think that was useful information.

**Comment by valeriob01** [comment]
I need to verify what gpuowl versions I have on my machines, the machine with amdgpu-pro needs NO_ASM and it is where this happens. I find load info is useful and I would like to see it again.

**Comment by valeriob01** [comment]
Ok. The machine where this happens has version 6.11, while other machines have version 6.10 and the load line is present.

**Comment by valeriob01** [comment]
I noticed at first you removed the GHz display, after the cpu name display, and now the "load" line, thus it comes to mind if you are shrinking available info for gpuowl to be useful in a broad sense, but particularly for benchmarking, the load line in the log is very useful, suppose I run a benchmark multiple times against the same exponent, say for 100000 iterations each, at each run the load line tells us a lot of info which is hard to extract without it.

**Comment by selroc** [comment]
For the time being that machine with version 6.11 is now dismissed, and I refrain from upgrading other machines until the load line is back.

**Comment by preda** [comment]
Which information from the load line do you need?

**Comment by valeriob01** [comment]
> Which information from the load line do you need?

The residue I don't need it, the rest of line is useful info.

**Comment by valeriob01** [comment]
Thinking of it more in-depth. The load file and the K can be derived from other lines, thus only the Block Size is really useful.

**Comment by preda** [comment]
Sound good, I agree I'll add that information back as it's not anywhere
else.

**Comment by valeriob01** [comment]
> Sound good, I agree I'll add that information back as it's not anywhere else.

I noticed that the K shown on the first log line after the load line isn't the same shown on the load line. That is because some iterations are done before showing the first log line. So also the K is needed with the Block Size, it cannot be derived from other lines.

**Comment by preda** [comment]
I'm adding the loading line back. There is work-in-progress on the branch "proof" if you'd like to see it earlier.

**Comment by preda** [comment]
added back in master
