### ISSUE TITLE
Code for gpu information

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#68]
Not really an issue, maybe an addition, I have adapted this chunk of code from another library, it returns various gpu properties.
https://github.com/valeriob01/gpuinfo

The sense of this addition is towards making gpuowl a trusted client, by returning exact GPU names and other information, so that they can appear inside the JSON result sent back to the server.

**Comment by selroc** [comment]
> Not really an issue, maybe an addition, I have adapted this chunk of code from another library, it returns various gpu properties.
> https://github.com/valeriob01/gpuinfo
> 
> The sense of this addition is towards making gpuowl a trusted client, by returning exact GPU names and other information, so that they can appear inside the JSON result sent back to the server.

Reading clwrap.cpp the features are already there, no need to add anything, we just need to actually log/display the data that can be collected with getBoardName(), getHwName(), getFreq(). The only feature I didn't find in clwrap.cpp is the one to collect Global Mem Size.

**Comment by valeriob01** [comment]
> > Not really an issue, maybe an addition, I have adapted this chunk of code from another library, it returns various gpu properties.
> > https://github.com/valeriob01/gpuinfo
> > The sense of this addition is towards making gpuowl a trusted client, by returning exact GPU names and other information, so that they can appear inside the JSON result sent back to the server.
> 
> Reading clwrap.cpp the features are already there, no need to add anything, we just need to actually log/display the data that can be collected with getBoardName(), getHwName(), getFreq(). The only feature I didn't find in clwrap.cpp is the one to collect Global Mem Size.

I think gpuowl can set a 'default cpu name' for the -cpu argument using getBoardName() and getHwName(), maybe with the addition of the GPU ordinal from the -device argument.

**Comment by preda** [comment]
OK I'm slowly looking into this, sorry for the delay. I need to make a few preliminary changes to the way the default device (i.e. -device not specified) is handled.

**Comment by preda** [comment]
Implemented to some degree, re-open if needed.
