### ISSUE TITLE
primenet.py - when there's no blank line at the end of worktodo

### ISSUE THREAD

**Issue by k3ack3r** [preda/gpuowl#72]
the next assignment goes to the previous line like
PFactor=N/A,1,2,9255193,-1,77,2PFactor=N/A,1,2,9751933,-1,77,2

**Comment by preda** [comment]
Yes, but what would you see as a solution -- reading what is already in the file, to check whether it ends with \n or not, and add it if needed? too complicated, and likely will break in some way when handling windows newlines.

I think it's good practice to end the file with a newline, so let's make that a requirement.
