### ISSUE TITLE
ROCm 2.10: warning: argument unused during compilation: '-I .'

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#74]
```
warning: argument unused during compilation: '-I .'                                                                                                          
```

and ROCm is slower than previous version.

**Comment by preda** [comment]
I confirm that this is not a gpuowl bug/issues, but a ROCm OpenCL compiler issue. A similar issue was even reported in the past to ROCm, fixed then, and now came back. Please report to ROCm.

ROCm being slower than previous version -- unfortunatelly this is becoming a trend. Again not a gpuowl issue though.
