### ISSUE TITLE
build eror on msys2/windows

### ISSUE THREAD

**Issue by k3ack3r** [preda/gpuowl#76]
`GmpUtil.cpp: In function 'mpz_class {anonymous}::powerSmooth(u32, u32)':
GmpUtil.cpp:26:28: error: call of overloaded '__gmp_expr(<brace-enclosed initializer list>)' is ambiguous
   26 |   mpz_class a{u64(exp) << 8}; // boost 2s.
      |                            ^
In file included from GmpUtil.h:6,
                 from GmpUtil.cpp:3:
C:/msys64/mingw64/include/gmpxx.h:1502:3: note: candidate: '__gmp_expr<__mpz_struct [1], __mpz_struct [1]>::__gmp_expr(double)'
 1502 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/gmpxx.h:1502:3: note: candidate: '__gmp_expr<__mpz_struct [1], __mpz_struct [1]>::__gmp_expr(float)'
 1502 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/gmpxx.h:1502:3: note: candidate: '__gmp_expr<__mpz_struct [1], __mpz_struct [1]>::__gmp_expr(long unsigned int)'
 1502 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/gmpxx.h:1502:3: note: candidate: '__gmp_expr<__mpz_struct [1], __mpz_struct [1]>::__gmp_expr(long int)'
 1502 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/gmpxx.h:1502:3: note: candidate: '__gmp_expr<__mpz_struct [1], __mpz_struct [1]>::__gmp_expr(short unsigned int)'
 1502 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/gmpxx.h:1502:3: note: candidate: '__gmp_expr<__mpz_struct [1], __mpz_struct [1]>::__gmp_expr(short int)'
 1502 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/gmpxx.h:1502:3: note: candidate: '__gmp_expr<__mpz_struct [1], __mpz_struct [1]>::__gmp_expr(unsigned int)'
 1502 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/gmpxx.h:1502:3: note: candidate: '__gmp_expr<__mpz_struct [1], __mpz_struct [1]>::__gmp_expr(int)'
 1502 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/gmpxx.h:1502:3: note: candidate: '__gmp_expr<__mpz_struct [1], __mpz_struct [1]>::__gmp_expr(unsigned char)'
 1502 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/gmpxx.h:1502:3: note: candidate: '__gmp_expr<__mpz_struct [1], __mpz_struct [1]>::__gmp_expr(signed char)'
 1502 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/gmpxx.h:1492:3: note: candidate: '__gmp_expr<__mpz_struct [1], __mpz_struct [1]>::__gmp_expr(__gmp_expr<__mpz_struct [1], __mpz_struct [1]>&&)'
 1492 |   __gmp_expr(__gmp_expr &&z)
      |   ^~~~~~~~~~
C:/msys64/mingw64/include/gmpxx.h:1490:3: note: candidate: '__gmp_expr<__mpz_struct [1], __mpz_struct [1]>::__gmp_expr(const __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&)'
 1490 |   __gmp_expr(const __gmp_expr &z) { mpz_init_set(mp, z.mp); }
      |   ^~~~~~~~~~
make: *** [Makefile:30: GmpUtil.o] Error 1

`

**Comment by preda** [comment]
hopefully fixed?
