### ISSUE TITLE
Adaptive step too frequent GEC

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#77]
![image](https://user-images.githubusercontent.com/25838910/70068049-963a6d80-15ef-11ea-9c0f-da6b7936a3df.png)

**Comment by preda** [comment]
Try setting -log to a small value. Try without log, or with a higher value e.g. 100'000

**Comment by valeriob01** [comment]
I have tryed out -log 100000 and without -log and -log 10000, not much difference.

**Comment by preda** [comment]
Then did you, by any chance, set a small block size such as -block 100 ?

**Comment by valeriob01** [comment]
I have -block 400

**Comment by preda** [comment]
OK then I need to look into this; if anything changes let me know.

**Comment by valeriob01** [comment]
> OK then I need to look into this; if anything changes let me know.

even with -block 1000 the output is the same.

**Comment by valeriob01** [comment]
On error gpuowl restarted exactly from the % it was before the error. No rollback at all, this is nice but I think it has much overhead.

**Comment by valeriob01** [comment]
Please look this issue soon, I suspect since we are doing a check at every log step, it affects savefiles too.

**Comment by preda** [comment]
Could you please print the startup messages? I'm in particular interested in seeing: the gpuowl version, and the configuration, in particular -log value. A -log is the only thing that IMO explains the behavior you see. You don't see the spinner BTW?

**Comment by valeriob01** [comment]
```
gpuowl -dir /home/sel/gpuowl -use FMA_X2 -use MERGED_MIDDLE -user selroc -block 1000 -log 10000 -cpu R7c -device 0 -use T2_SHUFFLE
2019-12-12 09:16:00 gpuowl v6.11-83-ge270393
2019-12-12 09:16:00 Note: no config.txt file found
2019-12-12 09:16:00 config: -dir /home/sel/gpuowl -use FMA_X2 -use MERGED_MIDDLE -user selroc -block 1000 -log 10000 -cpu R7c -device 0 -use T2_SHUFFLE 
2019-12-12 09:16:00 99037357 FFT 5632K: Width 256x4, Height 64x4, Middle 11; 17.17 bits/word
2019-12-12 09:16:01 OpenCL args "-DEXP=99037357u -DWIDTH=1024u -DSMALL_HEIGHT=256u -DMIDDLE=11u -DWEIGHT_STEP=0x1.c64364243c065p+0 -DIWEIGHT_STEP=0x1.20899c4242e24p-1 -DWEIGHT_BIGSTEP=0x1.ae89f995ad3adp+0 -DIWEIGHT_BIGSTEP=0x1.306fe0a31b715p-1 -DAMDGPU=1 -DFMA_X2=1 -DMERGED_MIDDLE=1 -DT2_SHUFFLE=1  -I. -cl-fast-relaxed-math -cl-std=CL2.0"
1 warning generated.
2019-12-12 09:16:02 warning: argument unused during compilation: '-I .'

2019-12-12 09:16:02 OpenCL compilation in 1.65 s
2019-12-12 09:16:04 99037357 OK 70360000 loaded: blockSize 1000, 9c3efa82a6779f3e
2019-12-12 09:16:06 99037357 OK 70362000  71.05%;  882 us/it (min  881  881); ETA 0d 07:02; 43615f2636fa96ce (check 0.97s)
2019-12-12 09:16:14 99037357 OK 70370000  71.05%;  883 us/it (min  882  881); ETA 0d 07:02; 42d98cc6ae95a492 (check 0.97s)
2019-12-12 09:16:18 Stopping, please wait..
2019-12-12 09:16:20 99037357 OK 70375000  71.06%;  884 us/it (min  882  881); ETA 0d 07:02; 7454d75c8a9ce743 (check 0.97s)
2019-12-12 09:16:20 Exiting because "stop requested"
2019-12-12 09:16:20 Bye

```

**Comment by preda** [comment]
it seems you have a "-log 10000" in config. That explains the behavior you see.

**Comment by valeriob01** [comment]
> it seems you have a "-log 10000" in config. That explains the behavior you see.

Sorry Mihai but I have now specified -log 50000 and I see the same behavior. Can you please disable the adaptive step until we debug this issue?

**Comment by valeriob01** [comment]
> > it seems you have a "-log 10000" in config. That explains the behavior you see.
> 
> Sorry Mihai but I have now specified -log 50000 and I see the same behavior. Can you please disable the adaptive step until we debug this issue?

Now I have removed the -log argument, same behavior.

**Comment by preda** [comment]
There is no adaptive step in play here, that only comes when there are errors and reduces the check step. As I see you have no errors, so that's not what's happening. Are you sure you don't have some other settings left in the file config.txt? If it's not the -log I have no idea why you see a check every 10k.

**Comment by selroc** [comment]
> There is no adaptive step in play here, that only comes when there are errors and reduces the check step. As I see you have no errors, so that's not what's happening. Are you sure you don't have some other settings left in the file config.txt? If it's not the -log I have no idea why you see a check every 10k.

the madness here is that I do not use a config.txt file, I specify everything on the command-line.
I have always done with -log 10000, varying block size from gpu to gpu, but basically the GEC was every "-block" value , now it seems to be every "-log" value.

**Comment by valeriob01** [comment]
> > There is no adaptive step in play here, that only comes when there are errors and reduces the check step. As I see you have no errors, so that's not what's happening. Are you sure you don't have some other settings left in the file config.txt? If it's not the -log I have no idea why you see a check every 10k.
> 
> the madness here is that I do not use a config.txt file, I specify everything on the command-line.
> I have always done with -log 10000, varying block size from gpu to gpu, but basically the GEC was every "-block" value , now it seems to be every "-log" value.

To explain a bit better, I have removed the -log argument and seen the same behavior, an OK at every line, then I have tried -log 50000 and seen the same behavior, an OK at every line. Whatever I specify or omit, the behavior is now an OK at every log line.

**Comment by valeriob01** [comment]
> There is no adaptive step in play here, that only comes when there are errors and reduces the check step. As I see you have no errors, so that's not what's happening. Are you sure you don't have some other settings left in the file config.txt? If it's not the -log I have no idea why you see a check every 10k.

2019-12-12 09:16:00 Note: no config.txt file found

**Comment by preda** [comment]
on OK on every line is the new correct behavior. The issues was "it's too often every 10K its". It doesn't have to be every 10K, e.g. I use every 200K its. You have control over how often it happens, and the default is 200K. What is the bug?

**Comment by valeriob01** [comment]
> An OK on every line is the new intended behavior. The issues was "it's too often every 10K its". It doesn't have to be every 10K, e.g. I use every 200K its. You have control over how often it happens, and the default is 200K. What is the bug?
> 
> Am open to suggestions about a different behavior being desired by different people. I just don't consider those to be bugs.

Okay I am sorry for calling it a bug. I'm glad you finally said it is the intended behavior to have OK on every line. I suggest that we work on the documentation, after all gpuowl is becoming quite complex in tuning with all the parameters to chose from, and we could at least document the best combinations.

**Comment by preda** [comment]
Sounds good! I'll post something on the forums too about the changes in behavior, it's just that it's still a work in progress.

**Comment by valeriob01** [comment]
Observation: with the new behavior we have lost the ability to actually see when GEC is done, not important, just an observation.

**Comment by preda** [comment]
It is done every time you see "OK", that's the meaning of OK -- a check was done and passed.

**Comment by valeriob01** [comment]
> It is done every time you see "OK", that's the meaning of OK -- a check was done and passed.

I am misinterpreting the change, in my head it seems like the -block is being ignored, but maybe there was a change in the check too.

**Comment by valeriob01** [comment]
> > It is done every time you see "OK", that's the meaning of OK -- a check was done and passed.
> 
> I am misinterpreting the change, in my head it seems like the -block is being ignored, but maybe there was a change in the check too.

I see now, it is just that it was not clear before :-)
