### ISSUE TITLE
compiler flag -fconcepts needed with gcc 8.1

### ISSUE THREAD

**Issue by fjansson** [preda/gpuowl#8]
Hi,

I compiled the code in the master branch today, with gcc 8.1.0 on Arch Linux, getting the following error, and several like it.
```
in file included from args.h:4,
                 from gpuowl.cpp:5:
clwrap.h:247:41: error: use of ‘auto’ in parameter declaration only available with -fconcepts [-Werror]
 void setArg(cl_kernel k, int pos, const auto &value) { CHECK(clSetKernelArg(k, pos, sizeof(value), &value)); }
                                         ^~~~
```
Adding `-fconcepts` to the g++ line solved the problem, and gpuowl appears to work, i.e. runs without errors. I don't know how other gcc versions handle this.

I have an GeForce GTX 960, and found that gpuowl works with the flag `-tail split` but not without, for the exponent 75000001.

Cheers,
Fredrik

**Comment by preda** [comment]
done

**Comment by valeriob01** [comment]
With the last update to g++-8 it broke my system, it happens because I am using the debian experimental repository.
The fatal error when I run gpuowl is: terminate called after throwing an instance of 'char const*'

**Comment by preda** [comment]
This is something related to the .owl savefile. Maybe you have an older version of the savefile that can't be parsed. You could try moving it away to see if it helps. I plan to address this exception soon.

**Comment by valeriob01** [comment]
Yes, I removed the file and this helps. However it restarts from 0. Oh well, this happens when you experiment.
