### ISSUE TITLE
invalid savefiles after blackout

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#81]
```
2019-12-09 03:42:18 OpenCL compilation in 1.56 s
2019-12-09 03:42:18 '/home/xxx/gpuowl/98563771/98563771.owl' invalid
2019-12-09 03:42:18 '/home/xxx/gpuowl/98563771/98563771-old.owl' invalid
2019-12-09 03:42:18 Exiting because "invalid savefiles found, investigate why
```

I thought this is a extremely rare condition but it happened again.

**Comment by preda** [comment]
Could you please report the size of the savefiles? e.g. please report the output of:
> ls -la 98563771
> head -1 98563771/*.owl
did you lose all progress on that exponent?

The only explanation I can think of is that the OS keeps the data in RAM without flushing to disk for a long time. I'll try to address that.

**Comment by selroc** [comment]
> Could you please report the size of the savefiles? e.g. please report the output of:
> 
> > ls -la 98563771
> > head -1 98563771/*.owl
> > did you lose all progress on that exponent?
> 
> The only explanation I can think of is that the OS keeps the data in RAM without flushing to disk for a long time. I'll try to address that.

Ok, I will do so as soon as I am at home. Yes, I lost all progress, restarted from zero, because gpuowl didn't start until I deleted the savefiles.

**Comment by valeriob01** [comment]
> Could you please report the size of the savefiles? e.g. please report the output of:
> 
> > ls -la 98563771
> > head -1 98563771/*.owl
> > did you lose all progress on that exponent?
> 
> The only explanation I can think of is that the OS keeps the data in RAM without flushing to disk for a long time. I'll try to address that.

# ls -la 98563771
total 24072
drwxr-xr-x  2 root root     4096 Dec  9 08:08 .
drwxr-xr-x 32 sel  sel      4096 Dec  8 07:25 ..
-rw-r--r--  1 root root 12320525 Dec  9 08:08 98563771-old.owl
-rw-r--r--  1 root root 12320525 Dec  9 08:08 98563771.owl
root@compute06:/home/xxx/gpuowl# head -1 98563771/*.owl
==> 98563771/98563771-old.owl <==
OWL PRP 10 98563771 17000000 1000 807abe17095a7cc9 0

==> 98563771/98563771.owl <==
OWL PRP 10 98563771 17001000 1000 91e91e05b3864aae 0

**Comment by valeriob01** [comment]
> Could you please report the size of the savefiles? e.g. please report the output of:
> 
> > ls -la 98563771
> > head -1 98563771/*.owl
> > did you lose all progress on that exponent?
> 
> The only explanation I can think of is that the OS keeps the data in RAM without flushing to disk for a long time. I'll try to address that.

I am not sure but you could try with the fflush() instruction.

**Comment by preda** [comment]
I was thinking about getting the size and header of the affected ("bad") files. I think what you have now are the new, valid files, right? One way to preserve the broken ones would be to rename the "bad" folder 98563771 out of the way (to something like e.g. 98563771-powerfail )

**Comment by selroc** [comment]
> I was thinking about getting the size and header of the affected ("bad") files. I think what you have now are the new, valid files, right? One way to preserve the broken ones would be to rename the "bad" folder 98563771 out of the way (to something like e.g. 98563771-powerfail )

OK! I will do this test tomorrow.

**Comment by selroc** [comment]
> Could you please report the size of the savefiles? e.g. please report the output of:
> 
> > ls -la 98563771
> > head -1 98563771/*.owl
> > did you lose all progress on that exponent?
> 
> The only explanation I can think of is that the OS keeps the data in RAM without flushing to disk for a long time. I'll try to address that.

that makes no difference philosophically , however, I can get away with a bash script, or better a Cron line that issues the "sync" command every N minutes (this should already happen, but just in case I can force it).

**Comment by preda** [comment]
It seems the problem described was exarcebated by the high-frequency of savefile rotation (every 10K iterations), which probably left too little time to the OS to flush to disk using the default timers.

**Comment by valeriob01** [comment]
> It seems the problem described was exarcebated by the high-frequency of savefile rotation (every 10K iterations), which probably left too little time to the OS to flush to disk using the default timers.

I don't understand, I though the log step has nothing to do with the Block size of GEC. It now seems like the two concepts are conflated and I can't log 10000 anymore (which I always did). But then, even at log 50000 the behavior is the same (visually there is no difference).

**Comment by valeriob01** [comment]
> It seems the problem described was exarcebated by the high-frequency of savefile rotation (every 10K iterations), which probably left too little time to the OS to flush to disk using the default timers.

Now I am doing with -log 20000, will redo the test later. I have to simulate a blackout (pull the power cable).

**Comment by valeriob01** [comment]
> > It seems the problem described was exarcebated by the high-frequency of savefile rotation (every 10K iterations), which probably left too little time to the OS to flush to disk using the default timers.
> 
> Now I am doing with -log 20000, will redo the test later. I have to simulate a blackout (pull the power cable).

Okay I have done the test. The result is a bit disappointing, with -log 20000 same thing happens.
2019-12-16 15:05:16 Exiting because "invalid savefiles found, investigate why

**Comment by valeriob01** [comment]
Test data:

```
# ls -la 99180901-powerfail/
total 8
drwxr-xr-x  2 root root 4096 Dec 16 15:03 .
drwxr-xr-x 36 sel  sel  4096 Dec 16 15:10 ..
-rw-r--r--  1 root root    0 Dec 16 15:03 99180901-old.owl
-rw-r--r--  1 root root    0 Dec 16 15:03 99180901.owl

```

```
# head -1 99180901-powerfail/*.owl
==> 99180901-powerfail/99180901-old.owl <==

==> 99180901-powerfail/99180901.owl <==

```

**Comment by preda** [comment]
Thank you. I've been thinking about the proper way to handle this. In the end I feel like GpuOwl's resposability is to send the data properly to the OS, and from that point on it's in OS's care.

In this particular case, I feel like the OS should persist to disk in the ~ 20seconds between saves. I would expect to be somewhere a way to toggle/configure how long data can stay without being flushed. Anyway, a last resort is a cron job doing sync periodically.

I don't want to do a fsync from GpuOwl. I will think about adding one more savefile to the chain of "old" (i.e. keeping 3 instead of 2 savefiles).

**Comment by valeriob01** [comment]
> Thank you. I've been thinking about the proper way to handle this. In the end I feel like GpuOwl's resposability is to send the data properly to the OS, and from that point on it's in OS's care.
> 
> In this particular case, I feel like the OS should persist to disk in the ~ 20seconds between saves. I would expect to be somewhere a way to toggle/configure how long data can stay without being flushed. Anyway, a last resort is a cron job doing sync periodically.
> 
> I don't want to do a fsync from GpuOwl. I will think about adding one more savefile to the chain of "old" (i.e. keeping 3 instead of 2 savefiles).

Thank you too. I have already set up a cron line to sync every 5 minutes, the minimum delay specifiable in Cron is 1 minute, I will decrease the delay to 1 minute.

**Comment by valeriob01** [comment]
> > Thank you. I've been thinking about the proper way to handle this. In the end I feel like GpuOwl's resposability is to send the data properly to the OS, and from that point on it's in OS's care.
> > In this particular case, I feel like the OS should persist to disk in the ~ 20seconds between saves. I would expect to be somewhere a way to toggle/configure how long data can stay without being flushed. Anyway, a last resort is a cron job doing sync periodically.
> > I don't want to do a fsync from GpuOwl. I will think about adding one more savefile to the chain of "old" (i.e. keeping 3 instead of 2 savefiles).
> 
> Thank you too. I have already set up a cron line to sync every 5 minutes, the minimum delay specifiable in Cron is 1 minute, I will decrease the delay to 1 minute.

After two blackouts I can say the trick has solved the problem pretty well. A crontab line that issues the sync command every minute.

**Comment by valeriob01** [comment]
(ref. https://mersenneforum.org/showthread.php?p=550649#post550649)

After some more experimentation I found the following:

 - For M105-M106 exponents (the current PRP wavefront) both checkpoints are invalid after blackout and I need to run `remove_checkpoints_by_size.sh` to restart computing from scratch;
 - For M332-M333 exponents (current PRP_M100 wavefront) only one checkpoint is invalid, and the computation can restart from the previous one.

My system is Ubuntu Focal Fossa with ROCm 3.3

**Comment by valeriob01** [comment]
> (ref. https://mersenneforum.org/showthread.php?p=550649#post550649)
> (ref. https://www.selroc.systems/forum/sel-mersenne-prime-research-effort-and-other-plans/gpuowl-specific-material/162-invalid-savefiles-after-blackout)
> 
> After some more experimentation I found the following:
> 
>     * For M105-M106 exponents (the current PRP wavefront) both checkpoints are invalid after blackout and I need to run `remove_checkpoints_by_size.sh` to restart computing from scratch;
> 
>     * For M332-M333 exponents (current PRP_M100 wavefront) only one checkpoint is invalid, and the computation can restart from the previous one.
> 
> 
> My system is Ubuntu Focal Fossa with ROCm 3.3

I found this is not always true, but in the majority of cases it is.
