### ISSUE TITLE
Q: is it true that Linux kernel 5.4 enables gpu bulk moves?

### ISSUE THREAD

**Issue by selroc** [preda/gpuowl#88]
Bulk moves should improve performance.

**Comment by preda** [comment]
I don't remember any big performance changes. I don't expect bulk moves (I don't know exactly what that is) to have a big impact on GpuOwl, because the transfer gpu-host is minimal in this case.

**Comment by valeriob01** [comment]
> I don't remember any big performance changes. I don't expect bulk moves (I don't know exactly what that is) to have a big impact on GpuOwl, because the transfer gpu-host is minimal in this case.

That's true for kernel 5.4 because they have shifted that to kernel 5.5
For reference: https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-Linux-5.5-Early-WIP

**Comment by valeriob01** [comment]
For better reference, original patch post:
https://lists.freedesktop.org/archives/amd-gfx/2018-August/025014.html
