### ISSUE TITLE
Hang at program start

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#9]
If there is a problem with the gpu, then gpuowl will hang and go into a "D" state (uninterruptible sleep). In this situation the only way to stop the program is to reset the machine.

**Comment by valeriob01** [comment]
In some cases when gpuowl hangs at start it will break the N.owl file.
After a hang, the next time I run gpuowl it just says Bye and exits. I remove the N.owl file and gpuowl restarts from checkpoint.

**Comment by valeriob01** [comment]
Now I have installed the new driver amdgpu-pro 18.10, there was the same problem with the previous driver version, sometimes the program goes into D state at start, waiting for gpu I/O, but I guess this is some driver structural limitation, and I should investigate further.

**Comment by preda** [comment]
ok thanks, closing then.
