### ISSUE TITLE
ROCm 3.0 warning: is it good to upgrade?

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#91]
For ROCm 3.0 there is a gpuOwl warning

https://github.com/RadeonOpenCompute/ROCm#gpuowl-fails-with-memory-access-fault-error

**Comment by preda** [comment]
I personally can't get OpenCL to work on ROCm 3.0 at all, issue reported. As soon as I get OpenCL working I'll try to understand what the ROCm 3.0 problem is.

**Comment by valeriob01** [comment]
I have attempted to upgrade to rocm 3.0 on Debian. Like you reported I couldn't get opencl to work and had to rollback.

**Comment by preda** [comment]
I'm closing this issue, as I have no visibility on when ROCm 3.0 upgrade might work.

**Comment by valeriob01** [comment]
> I'm closing this issue, as I have no visibility on when ROCm 3.0 upgrade might work.

Furthermore their Resolution isn;t working because PRP values are sequentially growing.

**Comment by valeriob01** [comment]
> > I'm closing this issue, as I have no visibility on when ROCm 3.0 upgrade might work.
> 
> Furthermore their Resolution isn;t working because PRP values are sequentially growing.

https://github.com/RadeonOpenCompute/ROCm/issues/1020

**Comment by valeriob01** [comment]
Again for 3.1.0, is it good to upgrade?

**Comment by preda** [comment]
gpuowl execution is broken on ROCm 3.1 , not a good idead to upgrade unless with the goal of debugging.
