### ISSUE TITLE
device 0 unique_id is empty

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#96]
`2020-01-05 05:35:21 device 0, unique id ''
`

**Comment by preda** [comment]
That's normal, it indicates that the unique id is not available on that system.
The unique id is read from a file such as
/sys/class/drm/card0/device/unique_id
If this file does not exist on the system, there is no unique id that can be used.

**Comment by valeriob01** [comment]
Okay but it does exist for device 1:

-use NEW_FFT8,OLD_FFT5,NEW_FFT10: comma separated list of defines, see the #if tests in gpuowl.cl (used for perf tuning)
-device <N>        : select a specific device:
```
 -use NEW_FFT8,OLD_FFT5,NEW_FFT10: comma separated list of defines, see the #if tests in gpuowl.cl (used for perf tuning)
-device <N>        : select a specific device:
 0  : gfx906+sram-ecc-Vega 20 [Radeon VII] AMD
 1 2ae088c172fd5d13 : gfx906+sram-ecc-Vega 20 [Radeon VII] AMD

```

**Comment by valeriob01** [comment]
The kernel is 4.19. Looking at directory listing from card0 and card1 they have a different set of files:

```
ls /sys/class/drm/card0/device/
ari_enabled               consistent_dma_mask_bits  dma_mask_bits             firmware_node/            index                     max_link_speed            numa_node                 resource                  revision                  uevent
boot_vga                  current_link_speed        driver/                   graphics/                 irq                       max_link_width            power/                    resource0                 rom                       vendor
broken_parity_status      current_link_width        driver_override           i2c-1/                    label                     modalias                  remove                    resource2                 subsystem/                
class                     d3cold_allowed            drm/                      i2c-2/                    local_cpulist             msi_bus                   rescan                    resource2_wc              subsystem_device          
config                    device                    enable                    i2c-3/                    local_cpus                msi_irqs/                 reset                     resource4                 subsystem_vendor    
```

```
ls /sys/class/drm/card1/device/
aer_dev_correctable   class                     device           enable            i2c-7           max_link_width           mem_info_vram_total  pcie_bw                            pp_dpm_dcefclk  pp_features            pp_table   resource0_wc  rom               vbios_version
aer_dev_fatal         config                    df_cntr_avail    fw_version        i2c-9           mem_busy_percent         mem_info_vram_used   pcie_replay_count                  pp_dpm_fclk     pp_force_state         remove     resource2     subsystem         vendor
aer_dev_nonfatal      consistent_dma_mask_bits  dma_mask_bits    gpu_busy_percent  irq             mem_info_gtt_total       modalias             power                              pp_dpm_mclk     pp_mclk_od             rescan     resource2_wc  subsystem_device
ari_enabled           current_link_speed        driver           hwmon             local_cpulist   mem_info_gtt_used        msi_bus              power_dpm_force_performance_level  pp_dpm_pcie     pp_num_states          reset      resource4     subsystem_vendor
boot_vga              current_link_width        driver_override  i2c-11            local_cpus      mem_info_vis_vram_total  msi_irqs             power_dpm_state                    pp_dpm_sclk     pp_power_profile_mode  resource   resource5     uevent
broken_parity_status  d3cold_allowed            drm              i2c-5             max_link_speed  mem_info_vis_vram_used   numa_node            pp_cur_state                       pp_dpm_socclk   pp_sclk_od             resource0  revision      unique_id

```

**Comment by preda** [comment]
Interesting, quite surprising given they're both Radeon VIIs. But returning to unique_id, what would be a better behavior in this (unexpected) case of two GPUs, one with and one without unique_id?

**Comment by selroc** [comment]
> Interesting, quite surprising given they're both Radeon VIIs. But returning to unique_id, what would be a better behavior in this (unexpected) case of two GPUs, one with and one without unique_id?

The current behavior is good, as the unique_id file is absent for card0. Given both R7 are same brand, I try to find a reason for that difference.

**Comment by valeriob01** [comment]
> > Interesting, quite surprising given they're both Radeon VIIs. But returning to unique_id, what would be a better behavior in this (unexpected) case of two GPUs, one with and one without unique_id?
> 
> The current behavior is good, as the unique_id file is absent for card0. Given both R7 are same brand, I try to find a reason for that difference. Furthermore, the unique_id file should be absent on the 4.19 kernel !!!

The mysteries of Linux, now I have 4 boards, but boards 1,2,3 have unique_id files, board 0 lacks the files.

**Comment by preda** [comment]
Closing as there's nothing gpuowl can do in this situation, IMO.

**Comment by valeriob01** [comment]
> Closing as there's nothing gpuowl can do in this situation, IMO.

I guess there's a bug in the patch sent out from ROCm guys because other users are having the same issue. So please revise that code for unique_id in ROCm...

**Comment by valeriob01** [comment]
https://github.com/RadeonOpenCompute/ROCm/issues/310#issuecomment-581425303

**Comment by valeriob01** [comment]
Monitor.py is failing because of lack of files in card0:

```
tools# ls
counts.py  delta.sh  device.py	monitor.py  primenet.py  README.md
root@compute02:/home/sel/gpuowl/tools# ./monitor.py 
GPU UID            VDD   SCLK MCLK Mem-used Mem-busy PWR  FAN  Temp     PCIeErr
Traceback (most recent call last):
  File "./monitor.py", line 81, in <module>
    printInfo(devices, readSlow)
  File "./monitor.py", line 70, in printInfo
    gpu = readGpu(d, readSlow)
  File "./monitor.py", line 57, in readGpu
    hwmon = hwmonPath(device)
  File "./monitor.py", line 18, in hwmonPath
    return hwmonBase + os.listdir(hwmonBase)[0] + '/'
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/drm/card0/device/hwmon/'

```

**Comment by valeriob01** [comment]
> Monitor.py is failing because of lack of files in card0:
> 
> ```
> tools# ls
> counts.py  delta.sh  device.py	monitor.py  primenet.py  README.md
> root@compute02:/home/sel/gpuowl/tools# ./monitor.py 
> GPU UID            VDD   SCLK MCLK Mem-used Mem-busy PWR  FAN  Temp     PCIeErr
> Traceback (most recent call last):
>   File "./monitor.py", line 81, in <module>
>     printInfo(devices, readSlow)
>   File "./monitor.py", line 70, in printInfo
>     gpu = readGpu(d, readSlow)
>   File "./monitor.py", line 57, in readGpu
>     hwmon = hwmonPath(device)
>   File "./monitor.py", line 18, in hwmonPath
>     return hwmonBase + os.listdir(hwmonBase)[0] + '/'
> FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/drm/card0/device/hwmon/'
> ```

is it possible to skip the card if files are absent, and monitor the remaining cards ?

**Comment by valeriob01** [comment]
I have reinstalled Debian and ROCm but still the first board is missing the necessary files for monitoring. I guess it is endemic.
